$axure.loadCurrentPage({
  "url":"发布岗位.html",
  "generationDate":new Date(1463986584162.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e4aba6397fb0429b91f2c20a74edd736",
    "type":"Axure:Page",
    "name":"发布岗位",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"80ce9c189cae4423b8dfee6ad45767b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "size":{
              "width":1074,
              "height":2280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228d2addd70a4d418753bd79bb247646",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":1074,
                  "height":2280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布岗位/u0.png"}},
{
          "id":"e4ac74a9a35c46e7a5632a88ebf74434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":125},
            "size":{
              "width":808,
              "height":2065},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dbfec650814428f8eded4f06f47acfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":224,
                  "y":125},
                "size":{
                  "width":808,
                  "height":2065},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布岗位/u2.png"}},
{
          "id":"fae4a066432c4c928df2a674e8497454",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":197},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/发工资页/u25_line.png"}},
{
          "id":"111eed7f75f84ead8d9adb8acef1b000",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":0,
              "y":2247},
            "size":{
              "width":1074,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9321890eed11432e94a50831610f4f17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":0,
                  "y":2247},
                "size":{
                  "width":1074,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代发工资/u19.png"}},
{
          "id":"ff81b46c8eb84c359d417aa2685a20b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "size":{
              "width":1074,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64c2f823a490407a9b2b763680d09da7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "size":{
                  "width":1074,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代发工资/u21.png"}},
{
          "id":"16df9161c98a4470b60e6b673b2599f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":225,
              "y":325},
            "size":{
              "width":4,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d7708c32ac409aa5b4406bcc507b37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":225,
                  "y":325},
                "size":{
                  "width":4,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建代发岗位/u73.png"}},
{
          "id":"39713a7c8c174bfbb909abf5222c8dac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":224,
              "y":1376},
            "size":{
              "width":4,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe193ab15dc54422b42f1648bffb383a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":224,
                  "y":1376},
                "size":{
                  "width":4,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建代发岗位/u73.png"}},
{
          "id":"bff21c9123ea4bb1b3eb384873de6b31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":224,
              "y":1185},
            "size":{
              "width":4,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3f4fc649dc146c59c80a5f8d637f303",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":224,
                  "y":1185},
                "size":{
                  "width":4,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建代发岗位/u73.png"}},
{
          "id":"c1f678a810bc42a6a345366da8351003",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":989},
            "size":{
              "width":183,
              "height":30},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab6324a335664938817a78cd40b27fe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":989},
                "size":{
                  "width":183,
                  "height":30},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建代发岗位/u79.png"}},
{
          "id":"8661d82f20a14d1abd5fa9b2df8b81e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":930,
              "y":161},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f76622e5d7e249fe9a82fa5b75ef2eb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":930,
                  "y":161},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb4d8e2b61f846beb2688d40b107fd38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1538,
              "y":43},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd011cccf1654d14994df2dc740b16c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1538,
                  "y":43},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32ca0871ffb44107bb9d61422c05e290",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":217},
            "size":{
              "width":348,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c276106be35f42519e207e8a08972871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":217},
                "size":{
                  "width":348,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新建代发岗位/u17.png"}},
{
          "id":"8b34a1e6d8ea4671986480018007c973",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":312},
            "size":{
              "width":490,
              "height":850}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ffb93a0a13f4958bfb5f8f89bc51c80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":312},
                "size":{
                  "width":490,
                  "height":850}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布岗位/u23.png"}},
{
          "id":"48fb1a839c264f3ca02b32c8547f1874",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":1174},
            "size":{
              "width":445,
              "height":853}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7456293316fa4ead85da4d0164e49a6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":1174},
                "size":{
                  "width":445,
                  "height":853}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布岗位/u25.png"}},
{
          "id":"9d65ad5fc21c4f288f66ed71c9bcf760",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":2027},
            "size":{
              "width":476,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0de3382f066c49c9b20e5692190791e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":2027},
                "size":{
                  "width":476,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布岗位/u27.png"}},
{
          "id":"8eb0cd57a19d45968785277cb5b0caf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":266,
              "y":2040},
            "size":{
              "width":111,
              "height":40},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dfa8de899a6424d932011d01581cb50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":266,
                  "y":2040},
                "size":{
                  "width":111,
                  "height":40},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 发工资页",
                      "target":{
                        "targetType":"page",
                        "url":"发工资页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发布岗位/u29.png"}},
{
          "id":"8ef257f6def14d30b6f86dab5c030518",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":260,
              "y":161},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d01640585f141bca6c1fe6af253bd32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":260,
                  "y":161},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92ca17788c8c49f7b28cab744da36e8e",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":128},
            "size":{
              "width":170,
              "height":278}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55122771d45c4e91920415c1648e12ab",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":278}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6113761bae54d8eaa7666a3f4dc8d77",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":170,
                      "height":57}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2046badb88a4421d837a7be7afc3e478",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":170,
                          "height":57}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/代发工资/u5.png"}},
{
                  "id":"c8bca739b2a44135abd605c4af95b318",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":170,
                      "height":56}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"433ba1c1e8244732a514da78cc016ad2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":170,
                          "height":56}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/代发工资/u7.png"}},
{
                  "id":"c8655ea4256948e69463ed75cb1d6c5f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":113},
                    "size":{
                      "width":170,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8cbf70f7117e450e9e2267ef4c73f008",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":113},
                        "size":{
                          "width":170,
                          "height":55}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/代发工资/u9.png"}},
{
                  "id":"98fbcad76bb148a39111614f66f82900",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":168},
                    "size":{
                      "width":170,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa9b3e2de2534842a44ec6e487da2c00",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":168},
                        "size":{
                          "width":170,
                          "height":55}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/代发工资/u9.png"}},
{
                  "id":"9a45f61945034b408527d2cbe098f3f6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":223},
                    "size":{
                      "width":170,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25c508667d8545d4abc4472b67d1056f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":223},
                        "size":{
                          "width":170,
                          "height":55}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/代发工资/u13.png"}}]}]},
{
          "id":"9197e8b7495c447b852ecb315ee5eb7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":31,
              "y":125},
            "size":{
              "width":183,
              "height":60},
            "cornerRadiusTopLeft":"3",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.137254901960784}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c26a47e12dca4ea8ba346ccbe0bf0f78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":31,
                  "y":125},
                "size":{
                  "width":183,
                  "height":60},
                "cornerRadiusTopLeft":"3",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.137254901960784}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代发工资/u15.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "80ce9c189cae4423b8dfee6ad45767b3":{
      "scriptId":"u0"},
    "228d2addd70a4d418753bd79bb247646":{
      "scriptId":"u1"},
    "e4ac74a9a35c46e7a5632a88ebf74434":{
      "scriptId":"u2"},
    "4dbfec650814428f8eded4f06f47acfc":{
      "scriptId":"u3"},
    "fae4a066432c4c928df2a674e8497454":{
      "scriptId":"u4"},
    "111eed7f75f84ead8d9adb8acef1b000":{
      "scriptId":"u5"},
    "9321890eed11432e94a50831610f4f17":{
      "scriptId":"u6"},
    "ff81b46c8eb84c359d417aa2685a20b3":{
      "scriptId":"u7"},
    "64c2f823a490407a9b2b763680d09da7":{
      "scriptId":"u8"},
    "16df9161c98a4470b60e6b673b2599f4":{
      "scriptId":"u9"},
    "53d7708c32ac409aa5b4406bcc507b37":{
      "scriptId":"u10"},
    "39713a7c8c174bfbb909abf5222c8dac":{
      "scriptId":"u11"},
    "fe193ab15dc54422b42f1648bffb383a":{
      "scriptId":"u12"},
    "bff21c9123ea4bb1b3eb384873de6b31":{
      "scriptId":"u13"},
    "d3f4fc649dc146c59c80a5f8d637f303":{
      "scriptId":"u14"},
    "c1f678a810bc42a6a345366da8351003":{
      "scriptId":"u15"},
    "ab6324a335664938817a78cd40b27fe9":{
      "scriptId":"u16"},
    "8661d82f20a14d1abd5fa9b2df8b81e2":{
      "scriptId":"u17"},
    "f76622e5d7e249fe9a82fa5b75ef2eb1":{
      "scriptId":"u18"},
    "fb4d8e2b61f846beb2688d40b107fd38":{
      "scriptId":"u19"},
    "bd011cccf1654d14994df2dc740b16c9":{
      "scriptId":"u20"},
    "32ca0871ffb44107bb9d61422c05e290":{
      "scriptId":"u21"},
    "c276106be35f42519e207e8a08972871":{
      "scriptId":"u22"},
    "8b34a1e6d8ea4671986480018007c973":{
      "scriptId":"u23"},
    "0ffb93a0a13f4958bfb5f8f89bc51c80":{
      "scriptId":"u24"},
    "48fb1a839c264f3ca02b32c8547f1874":{
      "scriptId":"u25"},
    "7456293316fa4ead85da4d0164e49a6a":{
      "scriptId":"u26"},
    "9d65ad5fc21c4f288f66ed71c9bcf760":{
      "scriptId":"u27"},
    "0de3382f066c49c9b20e5692190791e9":{
      "scriptId":"u28"},
    "8eb0cd57a19d45968785277cb5b0caf2":{
      "scriptId":"u29"},
    "1dfa8de899a6424d932011d01581cb50":{
      "scriptId":"u30"},
    "8ef257f6def14d30b6f86dab5c030518":{
      "scriptId":"u31"},
    "3d01640585f141bca6c1fe6af253bd32":{
      "scriptId":"u32"},
    "92ca17788c8c49f7b28cab744da36e8e":{
      "scriptId":"u33"},
    "55122771d45c4e91920415c1648e12ab":{
      "scriptId":"u34"},
    "c6113761bae54d8eaa7666a3f4dc8d77":{
      "scriptId":"u35"},
    "2046badb88a4421d837a7be7afc3e478":{
      "scriptId":"u36"},
    "c8bca739b2a44135abd605c4af95b318":{
      "scriptId":"u37"},
    "433ba1c1e8244732a514da78cc016ad2":{
      "scriptId":"u38"},
    "c8655ea4256948e69463ed75cb1d6c5f":{
      "scriptId":"u39"},
    "8cbf70f7117e450e9e2267ef4c73f008":{
      "scriptId":"u40"},
    "98fbcad76bb148a39111614f66f82900":{
      "scriptId":"u41"},
    "aa9b3e2de2534842a44ec6e487da2c00":{
      "scriptId":"u42"},
    "9a45f61945034b408527d2cbe098f3f6":{
      "scriptId":"u43"},
    "25c508667d8545d4abc4472b67d1056f":{
      "scriptId":"u44"},
    "9197e8b7495c447b852ecb315ee5eb7b":{
      "scriptId":"u45"},
    "c26a47e12dca4ea8ba346ccbe0bf0f78":{
      "scriptId":"u46"}}});