$axure.loadCurrentPage({
  "url":"每日绩效.html",
  "generationDate":new Date(1454224753351.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"e0f8600c22594d899095d9c8c41900d7",
    "type":"Axure:Page",
    "name":"每日绩效",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cb0c751d36a24bac890a1f7eab28602a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":524,
              "y":597},
            "size":{
              "width":200,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9377e4d2a5224b128b9c411cd72d2abf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":524,
                  "y":597},
                "size":{
                  "width":200,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/每日绩效/u0.png"}},
{
          "id":"6057dabb87b44cd19a083d4a53e66003",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":760,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c2610df12e94b2e9a86c5eeaabb5d36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":760,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/每日绩效/u2.png"}},
{
          "id":"67e3417e58ee4dd3a5b7e12b231cb38a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":351,
              "y":33},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48ea2705fcc44221a41eb2564e0dbc8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":351,
                  "y":33},
                "size":{
                  "width":66,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78ad4b13bc124d15b2a58faa86787942",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":427,
              "y":33},
            "size":{
              "width":100,
              "height":17}},
          "adaptiveStyles":{
}},
{
          "id":"e5a2706f55df4191bc3050130c8e804c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":33},
            "size":{
              "width":66,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be16ad9b46274e8d8076a910812dd21c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":33},
                "size":{
                  "width":66,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6575abd6abfd47918c59622d3d4b9885",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":110,
              "y":33},
            "size":{
              "width":100,
              "height":17}},
          "adaptiveStyles":{
}},
{
          "id":"d7cb34305f5a4731b65f21308092297a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":214,
              "y":33},
            "size":{
              "width":100,
              "height":17}},
          "adaptiveStyles":{
}},
{
          "id":"abe13343e73d42489a06940fffde420c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":709,
              "y":32},
            "size":{
              "width":59,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ac007bab4e44748975ac6618b25c185",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":709,
                  "y":32},
                "size":{
                  "width":59,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏元件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/每日绩效/u11.png"}},
{
          "id":"6f79f69d8e0546ec9fcaa715246f5c64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF81BC43},
            "location":{
              "x":506,
              "y":331},
            "size":{
              "width":54,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"137d1e375436494f81d47d1889dd83bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF81BC43},
                "location":{
                  "x":506,
                  "y":331},
                "size":{
                  "width":54,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付宝取现流水/u54.png"}},
{
          "id":"79c88a8eef2e4c3aabcdbfa8d65da7b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF81BC43},
            "location":{
              "x":442,
              "y":331},
            "size":{
              "width":54,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db7cd351000b4117962c04f133f80ecf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF81BC43},
                "location":{
                  "x":442,
                  "y":331},
                "size":{
                  "width":54,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付宝取现流水/u54.png"}},
{
          "id":"80090c26faa24745a88c5794dbcd2f40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF81BC43},
            "location":{
              "x":398,
              "y":331},
            "size":{
              "width":34,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14b5d5c24c534ce1a56fdfcae6b52c8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF81BC43},
                "location":{
                  "x":398,
                  "y":331},
                "size":{
                  "width":34,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付宝取现流水/u58.png"}},
{
          "id":"0443bae86f88449bbd1de73d9ccfb5ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF81BC43},
            "location":{
              "x":354,
              "y":331},
            "size":{
              "width":34,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acc481511d1a412fa586ccdc969e6b61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF81BC43},
                "location":{
                  "x":354,
                  "y":331},
                "size":{
                  "width":34,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付宝取现流水/u58.png"}},
{
          "id":"fc530c1afcbd4ee8a78ba78063363277",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF81BC43},
            "location":{
              "x":310,
              "y":331},
            "size":{
              "width":34,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e2631cb4aaa4a51957efcb9e91b416d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF81BC43},
                "location":{
                  "x":310,
                  "y":331},
                "size":{
                  "width":34,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付宝取现流水/u58.png"}},
{
          "id":"b6f7d6f435584d60bb65a8c7d06dae73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF81BC43},
            "location":{
              "x":248,
              "y":331},
            "size":{
              "width":54,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"617609b49e944fd5835d5705cedcfb37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF81BC43},
                "location":{
                  "x":248,
                  "y":331},
                "size":{
                  "width":54,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付宝取现流水/u54.png"}},
{
          "id":"11b04cdce1584206bba005121cf11137",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF81BC43},
            "location":{
              "x":184,
              "y":331},
            "size":{
              "width":54,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71166592560143178910439cc90d1b29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF81BC43},
                "location":{
                  "x":184,
                  "y":331},
                "size":{
                  "width":54,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付宝取现流水/u54.png"}},
{
          "id":"25ad440f1b3e44a7b38912b89f13219d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":101},
            "size":{
              "width":760,
              "height":159}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2273128cfa646c593acffc4161d7391",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":87,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54a981209d7249ae801ab91e5ce29c69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":87,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u28.png"}},
{
              "id":"3729e574a1f746e0985c07a7c8973e57",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":38},
                "size":{
                  "width":87,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6bf67e508fd44f649cc8bc73b27cb69d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":38},
                    "size":{
                      "width":87,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/支付宝取现流水/u101.png"}},
{
              "id":"f38e51c3dd11411db9f933294f64ee5a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":78},
                "size":{
                  "width":87,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41a76c1956a24f2f97090bcd2d0ef690",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":78},
                    "size":{
                      "width":87,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/支付宝取现流水/u101.png"}},
{
              "id":"e6f222af18864aa58700125f06b26de4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":87,
                  "y":0},
                "size":{
                  "width":104,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cb7d2ae4739d492eb7e99680dde339f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":87,
                      "y":0},
                    "size":{
                      "width":104,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u30.png"}},
{
              "id":"a5547e32ab284021883ff344b33d4404",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":87,
                  "y":38},
                "size":{
                  "width":104,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff959b0e0d9a4af59429a4089b15050c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":87,
                      "y":38},
                    "size":{
                      "width":104,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u44.png"}},
{
              "id":"f2d69dd721a145b7af1bd0a5b0851bcb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":87,
                  "y":78},
                "size":{
                  "width":104,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a9097556b4a4d48854ced61e8f8ddca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":87,
                      "y":78},
                    "size":{
                      "width":104,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u44.png"}},
{
              "id":"762cb3793e6a4863b9e5218bf49f5f38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":631,
                  "y":0},
                "size":{
                  "width":129,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b921c55d46bb4b37b97ca2d80c9007ef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"15px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":631,
                      "y":0},
                    "size":{
                      "width":129,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u40.png"}},
{
              "id":"51f7a136229c4c88a948d5ae0f8a41d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":631,
                  "y":38},
                "size":{
                  "width":129,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9783047b7903482db229ff1b77e3f7a1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":631,
                      "y":38},
                    "size":{
                      "width":129,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u54.png"}},
{
              "id":"0935aa5a59b642cdb0dcd12442fb9037",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":631,
                  "y":78},
                "size":{
                  "width":129,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e497b370cd0428ca5b830476bcdfec0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":631,
                      "y":78},
                    "size":{
                      "width":129,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u54.png"}},
{
              "id":"9f2fbeaac6ad43c49db9de9936398341",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":191,
                  "y":0},
                "size":{
                  "width":105,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d91cfc6008354bd092255195d5b42783",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":191,
                      "y":0},
                    "size":{
                      "width":105,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u32.png"}},
{
              "id":"eec47cd51fa1461fb5f5550dbd436d90",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":191,
                  "y":38},
                "size":{
                  "width":105,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"64feae3188624f9288176d7d4d3d1309",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":191,
                      "y":38},
                    "size":{
                      "width":105,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u46.png"}},
{
              "id":"9a364c936d824f87b2d8b840e2664b33",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":191,
                  "y":78},
                "size":{
                  "width":105,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5875957513a4e35a188b8b0021df7b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":191,
                      "y":78},
                    "size":{
                      "width":105,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u46.png"}},
{
              "id":"2cc22a8367b54daf92bf5d8298a7bac5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":118},
                "size":{
                  "width":87,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"693b7f0653044ff38f3e997f46303a1f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":118},
                    "size":{
                      "width":87,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u70.png"}},
{
              "id":"390a0cb5db854d30b12c36dae2210436",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":87,
                  "y":118},
                "size":{
                  "width":104,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3cc11a4a8ece406eb15163b0974bc34f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":87,
                      "y":118},
                    "size":{
                      "width":104,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u72.png"}},
{
              "id":"05358037a8f244aeb87222765f94f405",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":191,
                  "y":118},
                "size":{
                  "width":105,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"429ae84697ee4346973b1b2ccbeab1c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":191,
                      "y":118},
                    "size":{
                      "width":105,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u74.png"}},
{
              "id":"a6d7d131477c4cef8680a61704e5c307",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":631,
                  "y":118},
                "size":{
                  "width":129,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c25d59cffe78483f851ddac5db03cea6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":631,
                      "y":118},
                    "size":{
                      "width":129,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u82.png"}},
{
              "id":"ea83b9c846134f04a574f80374b9a7b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":296,
                  "y":0},
                "size":{
                  "width":137,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c447c95507cb4323a344ea3f8cf3a539",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":296,
                      "y":0},
                    "size":{
                      "width":137,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u34.png"}},
{
              "id":"23d2346ee1a24ce29c7df86b2eeb3512",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":296,
                  "y":38},
                "size":{
                  "width":137,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ed38396f5994933b18de45357cd894a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":296,
                      "y":38},
                    "size":{
                      "width":137,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u48.png"}},
{
              "id":"4ee48f4992fa4d09946475344ce65e85",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":296,
                  "y":78},
                "size":{
                  "width":137,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c5cf03f77714ca08807523c8c7416b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":296,
                      "y":78},
                    "size":{
                      "width":137,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u48.png"}},
{
              "id":"1b989a99567041378bb57be6fb6c5ff7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":296,
                  "y":118},
                "size":{
                  "width":137,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4298b22df24440aa93ed5cf62894858a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":296,
                      "y":118},
                    "size":{
                      "width":137,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u76.png"}},
{
              "id":"9b22bef24d934e1dac729c76b2f3e998",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":433,
                  "y":0},
                "size":{
                  "width":92,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74005fa1d6894b459e4116417b8d73a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":433,
                      "y":0},
                    "size":{
                      "width":92,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u36.png"}},
{
              "id":"213fed22dfab4d7c9c22857fe5890c9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":433,
                  "y":38},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4bcf8670ec84002b43c80fbd6b4bbf8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":433,
                      "y":38},
                    "size":{
                      "width":92,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u50.png"}},
{
              "id":"0b1ed82af6094f80b87a2f6866eae697",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":433,
                  "y":78},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34b77b7cdbe84845b6b801c010acc4d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":433,
                      "y":78},
                    "size":{
                      "width":92,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u50.png"}},
{
              "id":"13c13804a97a4b4885dd80c12956784f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":433,
                  "y":118},
                "size":{
                  "width":92,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd77c41c91864c38ae175e4bb886abcc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":433,
                      "y":118},
                    "size":{
                      "width":92,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u78.png"}},
{
              "id":"27d5a9416a34462d8372f0eaf5687070",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":525,
                  "y":0},
                "size":{
                  "width":106,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e350bd7c63cf48bcbd059f4c6045776b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":525,
                      "y":0},
                    "size":{
                      "width":106,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u38.png"}},
{
              "id":"a51994146be94acf91aa13f22ec3ca83",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":525,
                  "y":38},
                "size":{
                  "width":106,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8cc50cbf2a4c4cd08ac4b2d3dc493c91",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":525,
                      "y":38},
                    "size":{
                      "width":106,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u52.png"}},
{
              "id":"53d73237a00c4796941310abf8a76401",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":525,
                  "y":78},
                "size":{
                  "width":106,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"550e53e1323d4efa9aa1b14ec32f5855",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":525,
                      "y":78},
                    "size":{
                      "width":106,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u52.png"}},
{
              "id":"0156df20efc84bcc87e1aaed35b6c520",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":525,
                  "y":118},
                "size":{
                  "width":106,
                  "height":41}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16e1fdba4c784d578fcb83463efbb98b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":525,
                      "y":118},
                    "size":{
                      "width":106,
                      "height":41}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/每日绩效/u80.png"}}]},
{
          "id":"85b9c202f70c4203a3b3319528896cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":20,
              "y":388},
            "size":{
              "width":341,
              "height":307}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36f601f5d4748ffa14229c65a567d7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":388},
                "size":{
                  "width":341,
                  "height":307}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"616454764aea4a97bccdb4d88c1ca403",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":372,
              "y":388},
            "size":{
              "width":341,
              "height":307}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"568ebc61c3cc40f483514e8bd61f3549",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":372,
                  "y":388},
                "size":{
                  "width":341,
                  "height":307}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1282f8da6dc4de69924781194a93bfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":723,
              "y":388},
            "size":{
              "width":341,
              "height":307}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e4fb49966da44858541f3502966f825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":723,
                  "y":388},
                "size":{
                  "width":341,
                  "height":307}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c20c7bcc59da4e1e927a18dd64fe9e4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":358,
              "y":424},
            "size":{
              "width":552,
              "height":308}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dda1034e94e4af4bdb23577b9fae857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":358,
                  "y":424},
                "size":{
                  "width":552,
                  "height":308}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec758329edf646c79fba6b8bf63936da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "location":{
              "x":895,
              "y":280},
            "size":{
              "width":435,
              "height":320},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11f9e3f8cb524bc89645a5685587f3ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "location":{
                  "x":895,
                  "y":280},
                "size":{
                  "width":435,
                  "height":320},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "cb0c751d36a24bac890a1f7eab28602a":{
      "scriptId":"u0"},
    "9377e4d2a5224b128b9c411cd72d2abf":{
      "scriptId":"u1"},
    "6057dabb87b44cd19a083d4a53e66003":{
      "scriptId":"u2"},
    "2c2610df12e94b2e9a86c5eeaabb5d36":{
      "scriptId":"u3"},
    "67e3417e58ee4dd3a5b7e12b231cb38a":{
      "scriptId":"u4"},
    "48ea2705fcc44221a41eb2564e0dbc8c":{
      "scriptId":"u5"},
    "78ad4b13bc124d15b2a58faa86787942":{
      "scriptId":"u6"},
    "e5a2706f55df4191bc3050130c8e804c":{
      "scriptId":"u7"},
    "be16ad9b46274e8d8076a910812dd21c":{
      "scriptId":"u8"},
    "6575abd6abfd47918c59622d3d4b9885":{
      "scriptId":"u9"},
    "d7cb34305f5a4731b65f21308092297a":{
      "scriptId":"u10"},
    "abe13343e73d42489a06940fffde420c":{
      "scriptId":"u11"},
    "6ac007bab4e44748975ac6618b25c185":{
      "scriptId":"u12"},
    "6f79f69d8e0546ec9fcaa715246f5c64":{
      "scriptId":"u13"},
    "137d1e375436494f81d47d1889dd83bc":{
      "scriptId":"u14"},
    "79c88a8eef2e4c3aabcdbfa8d65da7b4":{
      "scriptId":"u15"},
    "db7cd351000b4117962c04f133f80ecf":{
      "scriptId":"u16"},
    "80090c26faa24745a88c5794dbcd2f40":{
      "scriptId":"u17"},
    "14b5d5c24c534ce1a56fdfcae6b52c8b":{
      "scriptId":"u18"},
    "0443bae86f88449bbd1de73d9ccfb5ae":{
      "scriptId":"u19"},
    "acc481511d1a412fa586ccdc969e6b61":{
      "scriptId":"u20"},
    "fc530c1afcbd4ee8a78ba78063363277":{
      "scriptId":"u21"},
    "1e2631cb4aaa4a51957efcb9e91b416d":{
      "scriptId":"u22"},
    "b6f7d6f435584d60bb65a8c7d06dae73":{
      "scriptId":"u23"},
    "617609b49e944fd5835d5705cedcfb37":{
      "scriptId":"u24"},
    "11b04cdce1584206bba005121cf11137":{
      "scriptId":"u25"},
    "71166592560143178910439cc90d1b29":{
      "scriptId":"u26"},
    "25ad440f1b3e44a7b38912b89f13219d":{
      "scriptId":"u27"},
    "c2273128cfa646c593acffc4161d7391":{
      "scriptId":"u28"},
    "54a981209d7249ae801ab91e5ce29c69":{
      "scriptId":"u29"},
    "e6f222af18864aa58700125f06b26de4":{
      "scriptId":"u30"},
    "cb7d2ae4739d492eb7e99680dde339f7":{
      "scriptId":"u31"},
    "9f2fbeaac6ad43c49db9de9936398341":{
      "scriptId":"u32"},
    "d91cfc6008354bd092255195d5b42783":{
      "scriptId":"u33"},
    "ea83b9c846134f04a574f80374b9a7b7":{
      "scriptId":"u34"},
    "c447c95507cb4323a344ea3f8cf3a539":{
      "scriptId":"u35"},
    "9b22bef24d934e1dac729c76b2f3e998":{
      "scriptId":"u36"},
    "74005fa1d6894b459e4116417b8d73a4":{
      "scriptId":"u37"},
    "27d5a9416a34462d8372f0eaf5687070":{
      "scriptId":"u38"},
    "e350bd7c63cf48bcbd059f4c6045776b":{
      "scriptId":"u39"},
    "762cb3793e6a4863b9e5218bf49f5f38":{
      "scriptId":"u40"},
    "b921c55d46bb4b37b97ca2d80c9007ef":{
      "scriptId":"u41"},
    "3729e574a1f746e0985c07a7c8973e57":{
      "scriptId":"u42"},
    "6bf67e508fd44f649cc8bc73b27cb69d":{
      "scriptId":"u43"},
    "a5547e32ab284021883ff344b33d4404":{
      "scriptId":"u44"},
    "ff959b0e0d9a4af59429a4089b15050c":{
      "scriptId":"u45"},
    "eec47cd51fa1461fb5f5550dbd436d90":{
      "scriptId":"u46"},
    "64feae3188624f9288176d7d4d3d1309":{
      "scriptId":"u47"},
    "23d2346ee1a24ce29c7df86b2eeb3512":{
      "scriptId":"u48"},
    "9ed38396f5994933b18de45357cd894a":{
      "scriptId":"u49"},
    "213fed22dfab4d7c9c22857fe5890c9b":{
      "scriptId":"u50"},
    "a4bcf8670ec84002b43c80fbd6b4bbf8":{
      "scriptId":"u51"},
    "a51994146be94acf91aa13f22ec3ca83":{
      "scriptId":"u52"},
    "8cc50cbf2a4c4cd08ac4b2d3dc493c91":{
      "scriptId":"u53"},
    "51f7a136229c4c88a948d5ae0f8a41d1":{
      "scriptId":"u54"},
    "9783047b7903482db229ff1b77e3f7a1":{
      "scriptId":"u55"},
    "f38e51c3dd11411db9f933294f64ee5a":{
      "scriptId":"u56"},
    "41a76c1956a24f2f97090bcd2d0ef690":{
      "scriptId":"u57"},
    "f2d69dd721a145b7af1bd0a5b0851bcb":{
      "scriptId":"u58"},
    "4a9097556b4a4d48854ced61e8f8ddca":{
      "scriptId":"u59"},
    "9a364c936d824f87b2d8b840e2664b33":{
      "scriptId":"u60"},
    "b5875957513a4e35a188b8b0021df7b5":{
      "scriptId":"u61"},
    "4ee48f4992fa4d09946475344ce65e85":{
      "scriptId":"u62"},
    "0c5cf03f77714ca08807523c8c7416b2":{
      "scriptId":"u63"},
    "0b1ed82af6094f80b87a2f6866eae697":{
      "scriptId":"u64"},
    "34b77b7cdbe84845b6b801c010acc4d5":{
      "scriptId":"u65"},
    "53d73237a00c4796941310abf8a76401":{
      "scriptId":"u66"},
    "550e53e1323d4efa9aa1b14ec32f5855":{
      "scriptId":"u67"},
    "0935aa5a59b642cdb0dcd12442fb9037":{
      "scriptId":"u68"},
    "4e497b370cd0428ca5b830476bcdfec0":{
      "scriptId":"u69"},
    "2cc22a8367b54daf92bf5d8298a7bac5":{
      "scriptId":"u70"},
    "693b7f0653044ff38f3e997f46303a1f":{
      "scriptId":"u71"},
    "390a0cb5db854d30b12c36dae2210436":{
      "scriptId":"u72"},
    "3cc11a4a8ece406eb15163b0974bc34f":{
      "scriptId":"u73"},
    "05358037a8f244aeb87222765f94f405":{
      "scriptId":"u74"},
    "429ae84697ee4346973b1b2ccbeab1c6":{
      "scriptId":"u75"},
    "1b989a99567041378bb57be6fb6c5ff7":{
      "scriptId":"u76"},
    "4298b22df24440aa93ed5cf62894858a":{
      "scriptId":"u77"},
    "13c13804a97a4b4885dd80c12956784f":{
      "scriptId":"u78"},
    "dd77c41c91864c38ae175e4bb886abcc":{
      "scriptId":"u79"},
    "0156df20efc84bcc87e1aaed35b6c520":{
      "scriptId":"u80"},
    "16e1fdba4c784d578fcb83463efbb98b":{
      "scriptId":"u81"},
    "a6d7d131477c4cef8680a61704e5c307":{
      "scriptId":"u82"},
    "c25d59cffe78483f851ddac5db03cea6":{
      "scriptId":"u83"},
    "85b9c202f70c4203a3b3319528896cd9":{
      "scriptId":"u84"},
    "d36f601f5d4748ffa14229c65a567d7c":{
      "scriptId":"u85"},
    "616454764aea4a97bccdb4d88c1ca403":{
      "scriptId":"u86"},
    "568ebc61c3cc40f483514e8bd61f3549":{
      "scriptId":"u87"},
    "f1282f8da6dc4de69924781194a93bfd":{
      "scriptId":"u88"},
    "0e4fb49966da44858541f3502966f825":{
      "scriptId":"u89"},
    "c20c7bcc59da4e1e927a18dd64fe9e4e":{
      "scriptId":"u90"},
    "0dda1034e94e4af4bdb23577b9fae857":{
      "scriptId":"u91"},
    "ec758329edf646c79fba6b8bf63936da":{
      "scriptId":"u92"},
    "11f9e3f8cb524bc89645a5685587f3ce":{
      "scriptId":"u93"}}});