$axure.loadCurrentPage({
  "url":"兼客众包临时需求.html",
  "generationDate":new Date(1468978884753.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fa2a9ec0961046e5af80f474b8a9b1bd",
    "type":"Axure:Page",
    "name":"兼客众包临时需求",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0024e8c24f2c4439a4136ad8c16e6e67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":1000,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03273431c133413586936c51561e7ebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":1000,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/兼客众包临时需求/u0.png"}},
{
          "id":"ebdfa7e58877434b9881d8f01da04df4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":258.5,
              "y":330},
            "size":{
              "width":683,
              "height":221}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"452b224dfdcc45159df316dc7fad85b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "size":{
                  "width":89,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c7cc78d8c194fd5b7609c1b71842799",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "size":{
                      "width":89,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u3.png"}},
{
              "id":"bfa8e71951a648128898481b2de35297",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":87},
                "size":{
                  "width":89,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b3d53f60cece443f878915d9e45e34cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":87},
                    "size":{
                      "width":89,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u7.png"}},
{
              "id":"495b4a80fa9c4c62b18dd6d1c7aa989c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":0},
                "size":{
                  "width":594,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cfd414e468834e76ac3a22446998d6db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":89,
                      "y":0},
                    "size":{
                      "width":594,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u5.png"}},
{
              "id":"f4d34491df8d470590ada72013d31c17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":87},
                "size":{
                  "width":594,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a934340b19e449e95edffe1f7756087",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":89,
                      "y":87},
                    "size":{
                      "width":594,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u9.png"}},
{
              "id":"ae058b9579834f2bbe755674a8fcc30f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":132},
                "size":{
                  "width":89,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"59f30f7ac6504d678f4c7eb6ce0afa6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":132},
                    "size":{
                      "width":89,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u15.png"}},
{
              "id":"ba962129fe204e9cae6fddf1babcb22f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":132},
                "size":{
                  "width":594,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"940ca91cba3049e5a09429f5de768984",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":89,
                      "y":132},
                    "size":{
                      "width":594,
                      "height":41},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u17.png"}},
{
              "id":"356c8ad81cf4488da8713e7d25259650",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":173},
                "size":{
                  "width":89,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f0c2eff18a834ec08f24d18ec9d67789",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":173},
                    "size":{
                      "width":89,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u19.png"}},
{
              "id":"9271ef850b74481c9bfe573e9830da1d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":173},
                "size":{
                  "width":594,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a1696800d3114c448ebe4f2c1cc71f0b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":89,
                      "y":173},
                    "size":{
                      "width":594,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u21.png"}},
{
              "id":"17498ba674814b7686662d1809f80832",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":42},
                "size":{
                  "width":89,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8445297013694c93aa395c04da4f99a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":42},
                    "size":{
                      "width":89,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u7.png"}},
{
              "id":"161477d1beab4889b22916a9098f33ab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":42},
                "size":{
                  "width":594,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44e82c424cc0467bac41b83b03335b7d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":89,
                      "y":42},
                    "size":{
                      "width":594,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/兼客众包临时需求/u9.png"}}]},
{
          "id":"e116e0f294374c6d8c154c882a5d56ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"36px",
            "horizontalAlignment":"center",
            "location":{
              "x":433,
              "y":200},
            "size":{
              "width":431,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"620801dc096341c39de9fe50853eb4f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "location":{
                  "x":433,
                  "y":200},
                "size":{
                  "width":431,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53ea205a3f694499b9a5ce256fa2d34b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":333,
              "y":180},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"592fe419dbc1418685626697122dbff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":333,
                  "y":180},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/兼客众包临时需求/u25.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "0024e8c24f2c4439a4136ad8c16e6e67":{
      "scriptId":"u0"},
    "03273431c133413586936c51561e7ebd":{
      "scriptId":"u1"},
    "ebdfa7e58877434b9881d8f01da04df4":{
      "scriptId":"u2"},
    "452b224dfdcc45159df316dc7fad85b5":{
      "scriptId":"u3"},
    "1c7cc78d8c194fd5b7609c1b71842799":{
      "scriptId":"u4"},
    "495b4a80fa9c4c62b18dd6d1c7aa989c":{
      "scriptId":"u5"},
    "cfd414e468834e76ac3a22446998d6db":{
      "scriptId":"u6"},
    "17498ba674814b7686662d1809f80832":{
      "scriptId":"u7"},
    "8445297013694c93aa395c04da4f99a8":{
      "scriptId":"u8"},
    "161477d1beab4889b22916a9098f33ab":{
      "scriptId":"u9"},
    "44e82c424cc0467bac41b83b03335b7d":{
      "scriptId":"u10"},
    "bfa8e71951a648128898481b2de35297":{
      "scriptId":"u11"},
    "b3d53f60cece443f878915d9e45e34cd":{
      "scriptId":"u12"},
    "f4d34491df8d470590ada72013d31c17":{
      "scriptId":"u13"},
    "5a934340b19e449e95edffe1f7756087":{
      "scriptId":"u14"},
    "ae058b9579834f2bbe755674a8fcc30f":{
      "scriptId":"u15"},
    "59f30f7ac6504d678f4c7eb6ce0afa6f":{
      "scriptId":"u16"},
    "ba962129fe204e9cae6fddf1babcb22f":{
      "scriptId":"u17"},
    "940ca91cba3049e5a09429f5de768984":{
      "scriptId":"u18"},
    "356c8ad81cf4488da8713e7d25259650":{
      "scriptId":"u19"},
    "f0c2eff18a834ec08f24d18ec9d67789":{
      "scriptId":"u20"},
    "9271ef850b74481c9bfe573e9830da1d":{
      "scriptId":"u21"},
    "a1696800d3114c448ebe4f2c1cc71f0b":{
      "scriptId":"u22"},
    "e116e0f294374c6d8c154c882a5d56ca":{
      "scriptId":"u23"},
    "620801dc096341c39de9fe50853eb4f0":{
      "scriptId":"u24"},
    "53ea205a3f694499b9a5ce256fa2d34b":{
      "scriptId":"u25"},
    "592fe419dbc1418685626697122dbff7":{
      "scriptId":"u26"}}});