$axure.loadCurrentPage({
  "url":"代发工资.html",
  "generationDate":new Date(1463986582319.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d4885269240e41b0aa8ee29c1e681510",
    "type":"Axure:Page",
    "name":"代发工资",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bc6fefc1241942c3a3ed2a84edec2694",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"3447add0283d4746843bc0c3f25760c6"},
{
          "id":"e4ac74a9a35c46e7a5632a88ebf74434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":125},
            "size":{
              "width":808,
              "height":625},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dbfec650814428f8eded4f06f47acfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":224,
                  "y":125},
                "size":{
                  "width":808,
                  "height":625},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代发工资/u17.png"}},
{
          "id":"51067f5f302046709b85538376982d21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":820,
              "y":600},
            "size":{
              "width":150,
              "height":60},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a67000663ce44d5acd3697a41561b07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":820,
                  "y":600},
                "size":{
                  "width":150,
                  "height":60},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新建代发岗位",
                      "target":{
                        "targetType":"page",
                        "url":"新建代发岗位.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/代发工资/u25.png"}},
{
          "id":"b198ff93ab71432eb978c2a3881cb217",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":180},
            "size":{
              "width":510,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47020ed677814813ab89c9af27ab113e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":180},
                "size":{
                  "width":510,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代发工资/u27.png"}},
{
          "id":"fbeed761d7244afc90d1636ad281c35d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":1084,
              "y":260},
            "size":{
              "width":300,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d87854244ca4950bea2b6cf8280de60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":1084,
                  "y":260},
                "size":{
                  "width":300,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "3447add0283d4746843bc0c3f25760c6":{
      "packageId":"3447add0283d4746843bc0c3f25760c6",
      "type":"Axure:Master",
      "name":"代发工资WEB模板",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3025823a927649149200c8f411c1f28f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "size":{
                "width":1074,
                "height":866},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0f8efe15b78146569b1dfecaad969e66",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "size":{
                    "width":1074,
                    "height":866},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资/u1.png"}},
{
            "id":"b459e592af584004a8fa437f80619926",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":128},
              "size":{
                "width":170,
                "height":278}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2e2ed2e3bff144219f7490def1c1a7b1",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":170,
                    "height":278}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"6001ead4bb154f6b9678fbeeccc6f0ac",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":170,
                        "height":57}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"89ab1feb32b54ce09c97920125bdf1c3",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":170,
                            "height":57}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资/u5.png"}},
{
                    "id":"612210abc25140d690a0b8331be2a679",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":57},
                      "size":{
                        "width":170,
                        "height":56}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"98cc0b8c4ecc4afa9040f147a4d7fe59",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":57},
                          "size":{
                            "width":170,
                            "height":56}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资/u7.png"}},
{
                    "id":"fc9b7468e8c148dab667dc84b8a86413",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":113},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2f7e94d6b3eb4e63b2e0d9d5d1d2c836",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":113},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资/u9.png"}},
{
                    "id":"81fddc2c676346b3a7a4bc2392f806fb",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":168},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2476e6aba3eb45a5a221a1ebce5ecef8",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":168},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资/u9.png"}},
{
                    "id":"44e2ca1a92e64cf5ab89e6ec0ddefaae",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":223},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"02a0e4ebb9464cfeaad5ee7fcb38c1e7",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":223},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资/u13.png"}}]}]},
{
            "id":"550f9ab3a7b24ac094bec0816ab7ffd1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF6B7C9C},
              "location":{
                "x":32,
                "y":239},
              "size":{
                "width":183,
                "height":60},
              "cornerRadiusTopLeft":"3",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":5,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.137254901960784}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58f22461c7ca4c7aa7fcd6559bf47ac6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF6B7C9C},
                  "location":{
                    "x":32,
                    "y":239},
                  "size":{
                    "width":183,
                    "height":60},
                  "cornerRadiusTopLeft":"3",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.137254901960784}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资/u15.png"}},
{
            "id":"015c8e27a78d4fa79c2de220ae6e5890",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":224,
                "y":125},
              "size":{
                "width":808,
                "height":625},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "cornerRadiusTopLeft":"8"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d48724a8dcde4164b4d26a45707e6018",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":224,
                    "y":125},
                  "size":{
                    "width":808,
                    "height":625},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "cornerRadiusTopLeft":"8"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资/u17.png"}},
{
            "id":"7799fd4ee3c44f7b8473cd01e491f940",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF6B7C9C},
              "location":{
                "x":0,
                "y":783},
              "size":{
                "width":1074,
                "height":83}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cceb82e3e99d40f8a2ffca63f4e3fe0a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF6B7C9C},
                  "location":{
                    "x":0,
                    "y":783},
                  "size":{
                    "width":1074,
                    "height":83}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资/u19.png"}},
{
            "id":"4f89b782091b438aae6fe48d6a4a392e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF6B7C9C},
              "size":{
                "width":1074,
                "height":86}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35f376c828d24457b6e3475eaee164a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF6B7C9C},
                  "size":{
                    "width":1074,
                    "height":86}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资/u21.png"}}]}}},
  "objectPaths":{
    "bc6fefc1241942c3a3ed2a84edec2694":{
      "scriptId":"u0",
      "3025823a927649149200c8f411c1f28f":{
        "scriptId":"u1"},
      "0f8efe15b78146569b1dfecaad969e66":{
        "scriptId":"u2"},
      "b459e592af584004a8fa437f80619926":{
        "scriptId":"u3"},
      "2e2ed2e3bff144219f7490def1c1a7b1":{
        "scriptId":"u4"},
      "6001ead4bb154f6b9678fbeeccc6f0ac":{
        "scriptId":"u5"},
      "89ab1feb32b54ce09c97920125bdf1c3":{
        "scriptId":"u6"},
      "612210abc25140d690a0b8331be2a679":{
        "scriptId":"u7"},
      "98cc0b8c4ecc4afa9040f147a4d7fe59":{
        "scriptId":"u8"},
      "fc9b7468e8c148dab667dc84b8a86413":{
        "scriptId":"u9"},
      "2f7e94d6b3eb4e63b2e0d9d5d1d2c836":{
        "scriptId":"u10"},
      "81fddc2c676346b3a7a4bc2392f806fb":{
        "scriptId":"u11"},
      "2476e6aba3eb45a5a221a1ebce5ecef8":{
        "scriptId":"u12"},
      "44e2ca1a92e64cf5ab89e6ec0ddefaae":{
        "scriptId":"u13"},
      "02a0e4ebb9464cfeaad5ee7fcb38c1e7":{
        "scriptId":"u14"},
      "550f9ab3a7b24ac094bec0816ab7ffd1":{
        "scriptId":"u15"},
      "58f22461c7ca4c7aa7fcd6559bf47ac6":{
        "scriptId":"u16"},
      "015c8e27a78d4fa79c2de220ae6e5890":{
        "scriptId":"u17"},
      "d48724a8dcde4164b4d26a45707e6018":{
        "scriptId":"u18"},
      "7799fd4ee3c44f7b8473cd01e491f940":{
        "scriptId":"u19"},
      "cceb82e3e99d40f8a2ffca63f4e3fe0a":{
        "scriptId":"u20"},
      "4f89b782091b438aae6fe48d6a4a392e":{
        "scriptId":"u21"},
      "35f376c828d24457b6e3475eaee164a4":{
        "scriptId":"u22"}},
    "e4ac74a9a35c46e7a5632a88ebf74434":{
      "scriptId":"u23"},
    "4dbfec650814428f8eded4f06f47acfc":{
      "scriptId":"u24"},
    "51067f5f302046709b85538376982d21":{
      "scriptId":"u25"},
    "5a67000663ce44d5acd3697a41561b07":{
      "scriptId":"u26"},
    "b198ff93ab71432eb978c2a3881cb217":{
      "scriptId":"u27"},
    "47020ed677814813ab89c9af27ab113e":{
      "scriptId":"u28"},
    "fbeed761d7244afc90d1636ad281c35d":{
      "scriptId":"u29"},
    "4d87854244ca4950bea2b6cf8280de60":{
      "scriptId":"u30"}}});