$axure.loadCurrentPage({
  "url":"修改绑定的手机.html",
  "generationDate":new Date(1422494611583.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c1effe5b100447cf950e56af3442a066",
    "type":"Axure:Page",
    "name":"修改绑定的手机",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b25ae89b35ab46d398b7a459e9d51faf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"8f7c1e33fdd84da8a59cc938c1ac8a29"},
{
          "id":"1592464876c14809b6650a5217d0ff44",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":199}},
          "adaptiveStyles":{
},
          "masterId":"e6a322afade64533b6dcea058d50cff6"},
{
          "id":"c4cf6626608b424986bca70ec9179435",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":1150,
              "y":320},
            "size":{
              "width":540,
              "height":590}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08f2eb9188c54913975f71dc7df4e048",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":1150,
                  "y":320},
                "size":{
                  "width":540,
                  "height":590}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订阅意向/u52.png"}},
{
          "id":"080bb21b3aa447a9b3792901a2b82250",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":1293.5,
              "y":358},
            "size":{
              "width":253,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2612d23950714d14b82b2826b08cf9f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":1293.5,
                  "y":358},
                "size":{
                  "width":253,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25e1667677f74af4a1cfe5c71f9f43a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1210,
              "y":430},
            "size":{
              "width":440,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8eb744a8a1c4430a9d0e5d833881cce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1210,
                  "y":430},
                "size":{
                  "width":440,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd224ed5064845c3869e21b8ccdb4730",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":1223,
              "y":599},
            "size":{
              "width":397,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"693c8c05f87d462c94429832d87629a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":1223,
                  "y":599},
                "size":{
                  "width":397,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a5c35f5001c481fb444dfc3989304b2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1119}},
          "adaptiveStyles":{
},
          "masterId":"c33396e136e84705978bc1cddc754c63"},
{
          "id":"ed70391a4bb946c399a7ef204753e21c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":300,
              "y":199},
            "size":{
              "width":661,
              "height":910}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"488df48b2ddb494a916b7176b683767b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":300,
                  "y":199},
                "size":{
                  "width":661,
                  "height":910}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改密码/u72.png"}},
{
          "id":"3e51070e67084649b28c07be31bebafd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":365.5,
              "y":273},
            "size":{
              "width":530,
              "height":368}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"773d7da980dd469cb9690a24ef770e7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365.5,
                  "y":273},
                "size":{
                  "width":530,
                  "height":368}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改绑定的手机/u74.png"}}]}},
  "masters":{
    "8f7c1e33fdd84da8a59cc938c1ac8a29":{
      "packageId":"8f7c1e33fdd84da8a59cc938c1ac8a29",
      "type":"Axure:Master",
      "name":"学生版-导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9a630881230c4e48908fd19d927107ac",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF282828},
              "size":{
                "width":700,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ad22df17cd94eb9a2c039b6bf9e0f69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF282828},
                  "size":{
                    "width":700,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/搜索页/u27.png"}},
{
            "id":"6c3e696d8be645ed8a890058fbf53c1f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF282828},
              "location":{
                "x":710,
                "y":0},
              "size":{
                "width":251,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0390ef4322d84f87ba467a451764254b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF282828},
                  "location":{
                    "x":710,
                    "y":0},
                  "size":{
                    "width":251,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/搜索页/u29.png"}},
{
            "id":"94358e5cab33479f9b8d21b4136b6a2f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1920673c50f24e8f9d74b9d74f26e2d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/搜索页/u31.png"}},
{
            "id":"b40a635fb1044b58b38ba58d228d9737",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":10,
                "y":16},
              "size":{
                "width":180,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e02aa7f185d245d48a335795dafa775f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":10,
                    "y":16},
                  "size":{
                    "width":180,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f44085158c89487ea28ba40ac4e503e6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF282828},
              "location":{
                "x":0,
                "y":69},
              "size":{
                "width":280,
                "height":120}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ab29bb83105e47adb318e71cf1013bc9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF282828},
                  "location":{
                    "x":0,
                    "y":69},
                  "size":{
                    "width":280,
                    "height":120}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/搜索页/u35.png"}},
{
            "id":"3a042b36699b47f6bca3d9457794ed67",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF282828},
              "location":{
                "x":304,
                "y":69},
              "size":{
                "width":657,
                "height":120}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed97144eeed8448595b165bd639069c0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF282828},
                  "location":{
                    "x":304,
                    "y":69},
                  "size":{
                    "width":657,
                    "height":120}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/搜索页/u37.png"}},
{
            "id":"bd7b8a69bae24202885028e31465f87e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":48,
                "y":100},
              "size":{
                "width":184,
                "height":54}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5f1585d4164545aba64e1db854c554cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":48,
                    "y":100},
                  "size":{
                    "width":184,
                    "height":54}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-学生",
                        "target":{
                          "targetType":"page",
                          "url":"首页-学生.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b3bc7dbc056b4c16990f0d48c25c8472",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"36px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":520,
                "y":91},
              "size":{
                "width":208,
                "height":54}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"269199b3c44d46f5a6af7665df13bf9b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"36px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":520,
                    "y":91},
                  "size":{
                    "width":208,
                    "height":54}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c455af6e872e43cba9ff001de320220e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"36px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":728,
                "y":80},
              "size":{
                "width":222,
                "height":98}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8905530f993843d3a5f3d2fc729ac8d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"36px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":728,
                    "y":80},
                  "size":{
                    "width":222,
                    "height":98}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"24ec9665e8174c898bbe47a3471b6cab",
            "label":"",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":710,
                "y":0},
              "size":{
                "width":251,
                "height":60}},
            "adaptiveStyles":{
}},
{
            "id":"f4f62b7fe0554fecb193581593d9d1a4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"24px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":751,
                "y":16},
              "size":{
                "width":90,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5305332ea03429cabc78a0f7e140524",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"24px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":751,
                    "y":16},
                  "size":{
                    "width":90,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b2a3f2274ebc487d96706afd7ca555ac",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"36px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":1230,
                "y":142},
              "size":{
                "width":222,
                "height":98}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c24ba9feb504dee945f97debd0b928b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"36px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":1230,
                    "y":142},
                  "size":{
                    "width":222,
                    "height":98}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dea7cdac17414a1bb88cb3ac65815d79",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":353,
                "y":99.5},
              "size":{
                "width":97,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"790c0efdac6045d5bc967b6c69e9f541",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":353,
                    "y":99.5},
                  "size":{
                    "width":97,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "e6a322afade64533b6dcea058d50cff6":{
      "packageId":"e6a322afade64533b6dcea058d50cff6",
      "type":"Axure:Master",
      "name":"学生竖导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a65447667c74b4699007137b36610e4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":0,
                "y":190},
              "size":{
                "width":280,
                "height":910}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"75f5f271c9724807aab55e004b308fc8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":0,
                    "y":190},
                  "size":{
                    "width":280,
                    "height":910}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/完善简历/u186.png"}},
{
            "id":"f2e7f610f6e944cf8e2007d38505f9c8",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":37,
                "y":215},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf370835d30b4a2894dd3468512c6f6a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37,
                    "y":215},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d4ea0a72fb9b466eb63fc2a06cf7b938",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":37,
                "y":351},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c0161de2ad7641e2acf5201722583187",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37,
                    "y":351},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"58654681e7cb4cd685cbe95ba0dae784",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":37,
                "y":281},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"856eb016ce2e483997238c8a8f509fed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":37,
                    "y":281},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1484c1ca839945779d09f47b198e6e3e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":50,
                "y":401},
              "size":{
                "width":49,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"452ca5c424234215bcee0ec178bd306e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":50,
                    "y":401},
                  "size":{
                    "width":49,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ecb41e45d823462bb3952b3e4642eadb",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":50,
                "y":443},
              "size":{
                "width":49,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0827f7c35131497e97079bf2ef01bdad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":50,
                    "y":443},
                  "size":{
                    "width":49,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"617d0b4710d94ddd9458bbb8433f2474",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":31,
                "y":526},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c702e6d035c14bf5862300157ce158b2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":31,
                    "y":526},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ff17614d152940e1b14b5016c9775543",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":15,
                "y":700},
              "size":{
                "width":250,
                "height":190}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c27cf39321b43bf8b4df9bda46ac088",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":15,
                    "y":700},
                  "size":{
                    "width":250,
                    "height":190}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/完善简历/u200.png"}},
{
            "id":"8cabf022cea648d1be4d42a66ab5fde1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":15,
                "y":900},
              "size":{
                "width":250,
                "height":190}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"245c65da05e84b73bc4e7f764b9bb0b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":15,
                    "y":900},
                  "size":{
                    "width":250,
                    "height":190}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/完善简历/u200.png"}},
{
            "id":"3fb2ff9058304b9691d2fbb6550121d4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":31,
                "y":626.5},
              "size":{
                "width":65,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4025d46ab5a447359365bc7f44ddf67b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":31,
                    "y":626.5},
                  "size":{
                    "width":65,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ad88df994fe345a9aaea06f787eecd30",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":31,
                "y":479},
              "size":{
                "width":129,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d922c1921e5148e1b49d39a4f7181ff0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":31,
                    "y":479},
                  "size":{
                    "width":129,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a27b0e959c4044e48abcf524a2a3f03f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "location":{
                "x":31,
                "y":579},
              "size":{
                "width":161,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f4f30ef593e44f83a56720ab379afaad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":31,
                    "y":579},
                  "size":{
                    "width":161,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "c33396e136e84705978bc1cddc754c63":{
      "packageId":"c33396e136e84705978bc1cddc754c63",
      "type":"Axure:Master",
      "name":"底板",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fa0168c06474400a980b16a167c3ab3a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF282828},
              "location":{
                "x":-21,
                "y":-10},
              "size":{
                "width":961,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"621c0e72034f40c4a548568f8f35ad52",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF282828},
                  "location":{
                    "x":-21,
                    "y":-10},
                  "size":{
                    "width":961,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-游客/u80.png"}},
{
            "id":"0fdf77383ca04ee3b7d763fe4b128700",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":230,
                "y":16},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4773d7061a504ef69775e6e9a7d84fdf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":230,
                    "y":16},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"57963ae782054394b92c60b310e18e5c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":40,
                "y":16},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"43c95e31f3a3447486d0bb82048d9e81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":40,
                    "y":16},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2be50ab842cc409193e2c2aa63034ffd",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":743,
                "y":16},
              "size":{
                "width":73,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef7ab2c7516048a69684b080170b8a2f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":743,
                    "y":16},
                  "size":{
                    "width":73,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"773e83cbca6c46b08fcabc1cab6bed22",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":570,
                "y":16},
              "size":{
                "width":121,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"73e4c66e91d34723b33fbadc14aa73e4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":570,
                    "y":16},
                  "size":{
                    "width":121,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"32f97d1170414d89813a264c53a96dba",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":423,
                "y":16},
              "size":{
                "width":98,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0dc7d81dbe9c4993ba70a794c9a526db",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":423,
                    "y":16},
                  "size":{
                    "width":98,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "b25ae89b35ab46d398b7a459e9d51faf":{
      "scriptId":"u0",
      "9a630881230c4e48908fd19d927107ac":{
        "scriptId":"u1"},
      "7ad22df17cd94eb9a2c039b6bf9e0f69":{
        "scriptId":"u2"},
      "6c3e696d8be645ed8a890058fbf53c1f":{
        "scriptId":"u3"},
      "0390ef4322d84f87ba467a451764254b":{
        "scriptId":"u4"},
      "94358e5cab33479f9b8d21b4136b6a2f":{
        "scriptId":"u5"},
      "1920673c50f24e8f9d74b9d74f26e2d3":{
        "scriptId":"u6"},
      "b40a635fb1044b58b38ba58d228d9737":{
        "scriptId":"u7"},
      "e02aa7f185d245d48a335795dafa775f":{
        "scriptId":"u8"},
      "f44085158c89487ea28ba40ac4e503e6":{
        "scriptId":"u9"},
      "ab29bb83105e47adb318e71cf1013bc9":{
        "scriptId":"u10"},
      "3a042b36699b47f6bca3d9457794ed67":{
        "scriptId":"u11"},
      "ed97144eeed8448595b165bd639069c0":{
        "scriptId":"u12"},
      "bd7b8a69bae24202885028e31465f87e":{
        "scriptId":"u13"},
      "5f1585d4164545aba64e1db854c554cc":{
        "scriptId":"u14"},
      "b3bc7dbc056b4c16990f0d48c25c8472":{
        "scriptId":"u15"},
      "269199b3c44d46f5a6af7665df13bf9b":{
        "scriptId":"u16"},
      "c455af6e872e43cba9ff001de320220e":{
        "scriptId":"u17"},
      "8905530f993843d3a5f3d2fc729ac8d9":{
        "scriptId":"u18"},
      "24ec9665e8174c898bbe47a3471b6cab":{
        "scriptId":"u19"},
      "f4f62b7fe0554fecb193581593d9d1a4":{
        "scriptId":"u20"},
      "a5305332ea03429cabc78a0f7e140524":{
        "scriptId":"u21"},
      "b2a3f2274ebc487d96706afd7ca555ac":{
        "scriptId":"u22"},
      "2c24ba9feb504dee945f97debd0b928b":{
        "scriptId":"u23"},
      "dea7cdac17414a1bb88cb3ac65815d79":{
        "scriptId":"u24"},
      "790c0efdac6045d5bc967b6c69e9f541":{
        "scriptId":"u25"}},
    "1592464876c14809b6650a5217d0ff44":{
      "scriptId":"u26",
      "1a65447667c74b4699007137b36610e4":{
        "scriptId":"u27"},
      "75f5f271c9724807aab55e004b308fc8":{
        "scriptId":"u28"},
      "f2e7f610f6e944cf8e2007d38505f9c8":{
        "scriptId":"u29"},
      "cf370835d30b4a2894dd3468512c6f6a":{
        "scriptId":"u30"},
      "d4ea0a72fb9b466eb63fc2a06cf7b938":{
        "scriptId":"u31"},
      "c0161de2ad7641e2acf5201722583187":{
        "scriptId":"u32"},
      "58654681e7cb4cd685cbe95ba0dae784":{
        "scriptId":"u33"},
      "856eb016ce2e483997238c8a8f509fed":{
        "scriptId":"u34"},
      "1484c1ca839945779d09f47b198e6e3e":{
        "scriptId":"u35"},
      "452ca5c424234215bcee0ec178bd306e":{
        "scriptId":"u36"},
      "ecb41e45d823462bb3952b3e4642eadb":{
        "scriptId":"u37"},
      "0827f7c35131497e97079bf2ef01bdad":{
        "scriptId":"u38"},
      "617d0b4710d94ddd9458bbb8433f2474":{
        "scriptId":"u39"},
      "c702e6d035c14bf5862300157ce158b2":{
        "scriptId":"u40"},
      "ff17614d152940e1b14b5016c9775543":{
        "scriptId":"u41"},
      "8c27cf39321b43bf8b4df9bda46ac088":{
        "scriptId":"u42"},
      "8cabf022cea648d1be4d42a66ab5fde1":{
        "scriptId":"u43"},
      "245c65da05e84b73bc4e7f764b9bb0b4":{
        "scriptId":"u44"},
      "3fb2ff9058304b9691d2fbb6550121d4":{
        "scriptId":"u45"},
      "4025d46ab5a447359365bc7f44ddf67b":{
        "scriptId":"u46"},
      "ad88df994fe345a9aaea06f787eecd30":{
        "scriptId":"u47"},
      "d922c1921e5148e1b49d39a4f7181ff0":{
        "scriptId":"u48"},
      "a27b0e959c4044e48abcf524a2a3f03f":{
        "scriptId":"u49"},
      "f4f30ef593e44f83a56720ab379afaad":{
        "scriptId":"u50"}},
    "c4cf6626608b424986bca70ec9179435":{
      "scriptId":"u51"},
    "08f2eb9188c54913975f71dc7df4e048":{
      "scriptId":"u52"},
    "080bb21b3aa447a9b3792901a2b82250":{
      "scriptId":"u53"},
    "2612d23950714d14b82b2826b08cf9f2":{
      "scriptId":"u54"},
    "25e1667677f74af4a1cfe5c71f9f43a1":{
      "scriptId":"u55"},
    "c8eb744a8a1c4430a9d0e5d833881cce":{
      "scriptId":"u56"},
    "fd224ed5064845c3869e21b8ccdb4730":{
      "scriptId":"u57"},
    "693c8c05f87d462c94429832d87629a9":{
      "scriptId":"u58"},
    "0a5c35f5001c481fb444dfc3989304b2":{
      "scriptId":"u59",
      "fa0168c06474400a980b16a167c3ab3a":{
        "scriptId":"u60"},
      "621c0e72034f40c4a548568f8f35ad52":{
        "scriptId":"u61"},
      "0fdf77383ca04ee3b7d763fe4b128700":{
        "scriptId":"u62"},
      "4773d7061a504ef69775e6e9a7d84fdf":{
        "scriptId":"u63"},
      "57963ae782054394b92c60b310e18e5c":{
        "scriptId":"u64"},
      "43c95e31f3a3447486d0bb82048d9e81":{
        "scriptId":"u65"},
      "2be50ab842cc409193e2c2aa63034ffd":{
        "scriptId":"u66"},
      "ef7ab2c7516048a69684b080170b8a2f":{
        "scriptId":"u67"},
      "773e83cbca6c46b08fcabc1cab6bed22":{
        "scriptId":"u68"},
      "73e4c66e91d34723b33fbadc14aa73e4":{
        "scriptId":"u69"},
      "32f97d1170414d89813a264c53a96dba":{
        "scriptId":"u70"},
      "0dc7d81dbe9c4993ba70a794c9a526db":{
        "scriptId":"u71"}},
    "ed70391a4bb946c399a7ef204753e21c":{
      "scriptId":"u72"},
    "488df48b2ddb494a916b7176b683767b":{
      "scriptId":"u73"},
    "3e51070e67084649b28c07be31bebafd":{
      "scriptId":"u74"},
    "773d7da980dd469cb9690a24ef770e7c":{
      "scriptId":"u75"}}});