$axure.loadCurrentPage({
  "url":"发工资页.html",
  "generationDate":new Date(1463126744907.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bf9bc7709e1d40cfaa81cd1ce25fa701",
    "type":"Axure:Page",
    "name":"发工资页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9bd6e36a1b274a3a96475ff7de61e4c1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"3447add0283d4746843bc0c3f25760c6"},
{
          "id":"e4ac74a9a35c46e7a5632a88ebf74434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":125},
            "size":{
              "width":808,
              "height":625},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dbfec650814428f8eded4f06f47acfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":224,
                  "y":125},
                "size":{
                  "width":808,
                  "height":625},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代发工资-首页/u21.png"}},
{
          "id":"fae4a066432c4c928df2a674e8497454",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":191},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/代发工资-首页/u29_line.png"}},
{
          "id":"9dddd8b710844419b09589d6698ac22a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":270},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/代发工资-首页/u29_line.png"}},
{
          "id":"593c7329e63d48fe8748e2405169bfb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B7C9C,
              "opacity":1},
            "location":{
              "x":272,
              "y":233},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a7282f2abb840f5b29e461605b5e734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C,
                  "opacity":1},
                "location":{
                  "x":272,
                  "y":233},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3691bb784bd47a09ad8d1a96b7d3e40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":403,
              "y":233},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe2f1b886dd4a72a592d751377d4849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":403,
                  "y":233},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"566ab8b6d0dc4f18a1daaa3c42458b2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":391,
              "y":308},
            "size":{
              "width":108,
              "height":35},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aee973433f7b429585c6d94c9d0eb30d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":391,
                  "y":308},
                "size":{
                  "width":108,
                  "height":35},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 导入工资表",
                      "objectsToFades":[{
                          "objectPath":["60110304879a4374862214a5be28682c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发工资页/u35.png"}},
{
          "id":"27a9d3cb5395439b829eaa9eba0c4bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":260,
              "y":157},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3506ac93f9e4ab5a80b87ba7439abd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":260,
                  "y":157},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf87468c3bb94decbed233a3b4b2c34c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":287,
              "y":264},
            "size":{
              "width":18,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e84655f9cec465d93864616417cc1e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":287,
                  "y":264},
                "size":{
                  "width":18,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资页/u39.png"}},
{
          "id":"2cd56d949e924d5f90b01d2f1b5c2385",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":480,
              "y":445},
            "size":{
              "width":259,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43db0a433e3c4ca3bfbfbf5759e11664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":480,
                  "y":445},
                "size":{
                  "width":259,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74579d02456b49d981990fa1c3c319e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1090,
              "y":220},
            "size":{
              "width":370,
              "height":308}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70aafce4ac8b410d8fc12e8e870cd028",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1090,
                  "y":220},
                "size":{
                  "width":370,
                  "height":308}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a5c2584962c41a9a691b941ea791f95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1100,
              "y":600},
            "size":{
              "width":427,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75928150ac51401e951b11601dbb8ea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1100,
                  "y":600},
                "size":{
                  "width":427,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资页/u45.png"}},
{
          "id":"c6559a7b76ef431ba31f95f68b4e15e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":518,
              "y":327},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb70f217a704409cab8e93d44baf42a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":518,
                  "y":327},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4b8b8b5a0e5495abfc6dc6b872b9822",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":260,
              "y":308},
            "size":{
              "width":108,
              "height":35},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c596f5668643999f9383ed29fbc11e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":260,
                  "y":308},
                "size":{
                  "width":108,
                  "height":35},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发工资页/u35.png"}},
{
          "id":"60110304879a4374862214a5be28682c",
          "label":"导入工资表",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":87},
            "size":{
              "width":1074,
              "height":697},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"da87b299d5f54c15963788ac3ff3b01b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d6c833af64dd41c9b229aade18a9d068",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "location":{
                      "x":-1,
                      "y":-1},
                    "size":{
                      "width":1080,
                      "height":710},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48e015111f354c5286a4766382997183",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.3",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "location":{
                          "x":-1,
                          "y":-1},
                        "size":{
                          "width":1080,
                          "height":710},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发工资页/u52.png"}},
{
                  "id":"cb6a3f4c633745c4beba774a7eae5161",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":296,
                      "y":80},
                    "size":{
                      "width":624,
                      "height":465}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15af7292dea84ad89395f9e7ec18c70f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":296,
                          "y":80},
                        "size":{
                          "width":624,
                          "height":465}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发工资页/u54.png"}},
{
                  "id":"8113eb01a8044b8c96a6690feea08f89",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":885,
                      "y":83},
                    "size":{
                      "width":30,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 导入工资表",
                              "objectsToFades":[{
                                  "objectPath":["60110304879a4374862214a5be28682c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"a672f8416c754a8b8ef97afa270d5703",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":818,
                      "y":508},
                    "size":{
                      "width":82,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 导入工资表",
                              "objectsToFades":[{
                                  "objectPath":["60110304879a4374862214a5be28682c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"9ea97dd27cdf465293e29f92b3a2a244",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":715,
                      "y":508},
                    "size":{
                      "width":82,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 loading",
                              "objectsToFades":[{
                                  "objectPath":["098cf9d68d2f4d3fab7db4ba41ac4b6f"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 导入工资表",
                              "objectsToFades":[{
                                  "objectPath":["60110304879a4374862214a5be28682c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"098cf9d68d2f4d3fab7db4ba41ac4b6f",
          "label":"loading",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":87},
            "size":{
              "width":1074,
              "height":697},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"551e0e9645b648cfbba0ae6e654a9258",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fe0bd3850ab64447aae2a27eff1b75a1",
                  "label":"",
                  "parentDynamicPanel":"098cf9d68d2f4d3fab7db4ba41ac4b6f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "location":{
                      "x":-1,
                      "y":-1},
                    "size":{
                      "width":1080,
                      "height":891},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f622e796f6c248618455a28ba6c924ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"098cf9d68d2f4d3fab7db4ba41ac4b6f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.3",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "location":{
                          "x":-1,
                          "y":-1},
                        "size":{
                          "width":1080,
                          "height":891},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发工资页/u60.png"}},
{
                  "id":"7338b6ad15c240e498af1eebb8a605ab",
                  "label":"",
                  "parentDynamicPanel":"098cf9d68d2f4d3fab7db4ba41ac4b6f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":430,
                      "y":182},
                    "size":{
                      "width":307,
                      "height":238},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf12ba7dfd4e438e92fc3edca5f8f817",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"098cf9d68d2f4d3fab7db4ba41ac4b6f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":430,
                          "y":182},
                        "size":{
                          "width":307,
                          "height":238},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发工资页/u62.png"}},
{
                  "id":"07e84f13943d4bdfbdf19a31ba9b17c6",
                  "label":"",
                  "parentDynamicPanel":"098cf9d68d2f4d3fab7db4ba41ac4b6f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":470,
                      "y":281},
                    "size":{
                      "width":257,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ba48525f2524aa6b005c9cd817cb604",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"098cf9d68d2f4d3fab7db4ba41ac4b6f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":470,
                          "y":281},
                        "size":{
                          "width":257,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b9f518784e3042e7ab1ed9f287a09a73",
                  "label":"",
                  "parentDynamicPanel":"098cf9d68d2f4d3fab7db4ba41ac4b6f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":707,
                      "y":200},
                    "size":{
                      "width":20,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea1dec1664dc4e50aea9b36761a8a383",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"098cf9d68d2f4d3fab7db4ba41ac4b6f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":707,
                          "y":200},
                        "size":{
                          "width":20,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 loading",
                              "objectsToFades":[{
                                  "objectPath":["098cf9d68d2f4d3fab7db4ba41ac4b6f"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发工资-已有兼客（导入成功）",
                              "target":{
                                "targetType":"page",
                                "url":"发工资-已有兼客（导入成功）.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "3447add0283d4746843bc0c3f25760c6":{
      "packageId":"3447add0283d4746843bc0c3f25760c6",
      "type":"Axure:Master",
      "name":"代发工资WEB模板",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3025823a927649149200c8f411c1f28f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "size":{
                "width":1074,
                "height":866},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0f8efe15b78146569b1dfecaad969e66",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "size":{
                    "width":1074,
                    "height":866},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u1.png"}},
{
            "id":"b459e592af584004a8fa437f80619926",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":128},
              "size":{
                "width":170,
                "height":388}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2e2ed2e3bff144219f7490def1c1a7b1",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":170,
                    "height":388}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"6001ead4bb154f6b9678fbeeccc6f0ac",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":170,
                        "height":57}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"89ab1feb32b54ce09c97920125bdf1c3",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":170,
                            "height":57}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u5.png"}},
{
                    "id":"612210abc25140d690a0b8331be2a679",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":57},
                      "size":{
                        "width":170,
                        "height":56}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"98cc0b8c4ecc4afa9040f147a4d7fe59",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":57},
                          "size":{
                            "width":170,
                            "height":56}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u7.png"}},
{
                    "id":"fc9b7468e8c148dab667dc84b8a86413",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":113},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2f7e94d6b3eb4e63b2e0d9d5d1d2c836",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":113},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u9.png"}},
{
                    "id":"81fddc2c676346b3a7a4bc2392f806fb",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":168},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2476e6aba3eb45a5a221a1ebce5ecef8",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":168},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u9.png"}},
{
                    "id":"340ef66b12ac410ea87bb2abd152f41c",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":278},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3b9c76c38ae345819394c93eb2ed9503",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":278},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u9.png"}},
{
                    "id":"25878244aaad4e248693071b2e9cd7dc",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":333},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c31c192645b54426b719e87e667e6a3e",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":333},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u17.png"}},
{
                    "id":"44e2ca1a92e64cf5ab89e6ec0ddefaae",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":223},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"02a0e4ebb9464cfeaad5ee7fcb38c1e7",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":223},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u9.png"}}]}]},
{
            "id":"550f9ab3a7b24ac094bec0816ab7ffd1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF6B7C9C},
              "location":{
                "x":31.5,
                "y":460},
              "size":{
                "width":183,
                "height":60},
              "cornerRadiusTopLeft":"3",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":5,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.137254901960784}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58f22461c7ca4c7aa7fcd6559bf47ac6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF6B7C9C},
                  "location":{
                    "x":31.5,
                    "y":460},
                  "size":{
                    "width":183,
                    "height":60},
                  "cornerRadiusTopLeft":"3",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.137254901960784}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u19.png"}},
{
            "id":"015c8e27a78d4fa79c2de220ae6e5890",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":224,
                "y":125},
              "size":{
                "width":808,
                "height":625},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "cornerRadiusTopLeft":"8"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d48724a8dcde4164b4d26a45707e6018",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":224,
                    "y":125},
                  "size":{
                    "width":808,
                    "height":625},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "cornerRadiusTopLeft":"8"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u21.png"}},
{
            "id":"7799fd4ee3c44f7b8473cd01e491f940",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF6B7C9C},
              "location":{
                "x":0,
                "y":783},
              "size":{
                "width":1074,
                "height":83}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cceb82e3e99d40f8a2ffca63f4e3fe0a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF6B7C9C},
                  "location":{
                    "x":0,
                    "y":783},
                  "size":{
                    "width":1074,
                    "height":83}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u23.png"}},
{
            "id":"4f89b782091b438aae6fe48d6a4a392e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF6B7C9C},
              "size":{
                "width":1074,
                "height":86}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35f376c828d24457b6e3475eaee164a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF6B7C9C},
                  "size":{
                    "width":1074,
                    "height":86}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u25.png"}}]}}},
  "objectPaths":{
    "9bd6e36a1b274a3a96475ff7de61e4c1":{
      "scriptId":"u0",
      "3025823a927649149200c8f411c1f28f":{
        "scriptId":"u1"},
      "0f8efe15b78146569b1dfecaad969e66":{
        "scriptId":"u2"},
      "b459e592af584004a8fa437f80619926":{
        "scriptId":"u3"},
      "2e2ed2e3bff144219f7490def1c1a7b1":{
        "scriptId":"u4"},
      "6001ead4bb154f6b9678fbeeccc6f0ac":{
        "scriptId":"u5"},
      "89ab1feb32b54ce09c97920125bdf1c3":{
        "scriptId":"u6"},
      "612210abc25140d690a0b8331be2a679":{
        "scriptId":"u7"},
      "98cc0b8c4ecc4afa9040f147a4d7fe59":{
        "scriptId":"u8"},
      "fc9b7468e8c148dab667dc84b8a86413":{
        "scriptId":"u9"},
      "2f7e94d6b3eb4e63b2e0d9d5d1d2c836":{
        "scriptId":"u10"},
      "81fddc2c676346b3a7a4bc2392f806fb":{
        "scriptId":"u11"},
      "2476e6aba3eb45a5a221a1ebce5ecef8":{
        "scriptId":"u12"},
      "44e2ca1a92e64cf5ab89e6ec0ddefaae":{
        "scriptId":"u13"},
      "02a0e4ebb9464cfeaad5ee7fcb38c1e7":{
        "scriptId":"u14"},
      "340ef66b12ac410ea87bb2abd152f41c":{
        "scriptId":"u15"},
      "3b9c76c38ae345819394c93eb2ed9503":{
        "scriptId":"u16"},
      "25878244aaad4e248693071b2e9cd7dc":{
        "scriptId":"u17"},
      "c31c192645b54426b719e87e667e6a3e":{
        "scriptId":"u18"},
      "550f9ab3a7b24ac094bec0816ab7ffd1":{
        "scriptId":"u19"},
      "58f22461c7ca4c7aa7fcd6559bf47ac6":{
        "scriptId":"u20"},
      "015c8e27a78d4fa79c2de220ae6e5890":{
        "scriptId":"u21"},
      "d48724a8dcde4164b4d26a45707e6018":{
        "scriptId":"u22"},
      "7799fd4ee3c44f7b8473cd01e491f940":{
        "scriptId":"u23"},
      "cceb82e3e99d40f8a2ffca63f4e3fe0a":{
        "scriptId":"u24"},
      "4f89b782091b438aae6fe48d6a4a392e":{
        "scriptId":"u25"},
      "35f376c828d24457b6e3475eaee164a4":{
        "scriptId":"u26"}},
    "e4ac74a9a35c46e7a5632a88ebf74434":{
      "scriptId":"u27"},
    "4dbfec650814428f8eded4f06f47acfc":{
      "scriptId":"u28"},
    "fae4a066432c4c928df2a674e8497454":{
      "scriptId":"u29"},
    "9dddd8b710844419b09589d6698ac22a":{
      "scriptId":"u30"},
    "593c7329e63d48fe8748e2405169bfb5":{
      "scriptId":"u31"},
    "2a7282f2abb840f5b29e461605b5e734":{
      "scriptId":"u32"},
    "a3691bb784bd47a09ad8d1a96b7d3e40":{
      "scriptId":"u33"},
    "6fe2f1b886dd4a72a592d751377d4849":{
      "scriptId":"u34"},
    "566ab8b6d0dc4f18a1daaa3c42458b2f":{
      "scriptId":"u35"},
    "aee973433f7b429585c6d94c9d0eb30d":{
      "scriptId":"u36"},
    "27a9d3cb5395439b829eaa9eba0c4bb7":{
      "scriptId":"u37"},
    "a3506ac93f9e4ab5a80b87ba7439abd3":{
      "scriptId":"u38"},
    "bf87468c3bb94decbed233a3b4b2c34c":{
      "scriptId":"u39"},
    "5e84655f9cec465d93864616417cc1e4":{
      "scriptId":"u40"},
    "2cd56d949e924d5f90b01d2f1b5c2385":{
      "scriptId":"u41"},
    "43db0a433e3c4ca3bfbfbf5759e11664":{
      "scriptId":"u42"},
    "74579d02456b49d981990fa1c3c319e0":{
      "scriptId":"u43"},
    "70aafce4ac8b410d8fc12e8e870cd028":{
      "scriptId":"u44"},
    "0a5c2584962c41a9a691b941ea791f95":{
      "scriptId":"u45"},
    "75928150ac51401e951b11601dbb8ea8":{
      "scriptId":"u46"},
    "c6559a7b76ef431ba31f95f68b4e15e3":{
      "scriptId":"u47"},
    "eb70f217a704409cab8e93d44baf42a3":{
      "scriptId":"u48"},
    "b4b8b8b5a0e5495abfc6dc6b872b9822":{
      "scriptId":"u49"},
    "43c596f5668643999f9383ed29fbc11e":{
      "scriptId":"u50"},
    "60110304879a4374862214a5be28682c":{
      "scriptId":"u51"},
    "d6c833af64dd41c9b229aade18a9d068":{
      "scriptId":"u52"},
    "48e015111f354c5286a4766382997183":{
      "scriptId":"u53"},
    "cb6a3f4c633745c4beba774a7eae5161":{
      "scriptId":"u54"},
    "15af7292dea84ad89395f9e7ec18c70f":{
      "scriptId":"u55"},
    "8113eb01a8044b8c96a6690feea08f89":{
      "scriptId":"u56"},
    "a672f8416c754a8b8ef97afa270d5703":{
      "scriptId":"u57"},
    "9ea97dd27cdf465293e29f92b3a2a244":{
      "scriptId":"u58"},
    "098cf9d68d2f4d3fab7db4ba41ac4b6f":{
      "scriptId":"u59"},
    "fe0bd3850ab64447aae2a27eff1b75a1":{
      "scriptId":"u60"},
    "f622e796f6c248618455a28ba6c924ef":{
      "scriptId":"u61"},
    "7338b6ad15c240e498af1eebb8a605ab":{
      "scriptId":"u62"},
    "bf12ba7dfd4e438e92fc3edca5f8f817":{
      "scriptId":"u63"},
    "07e84f13943d4bdfbdf19a31ba9b17c6":{
      "scriptId":"u64"},
    "5ba48525f2524aa6b005c9cd817cb604":{
      "scriptId":"u65"},
    "b9f518784e3042e7ab1ed9f287a09a73":{
      "scriptId":"u66"},
    "ea1dec1664dc4e50aea9b36761a8a383":{
      "scriptId":"u67"}}});