$axure.loadCurrentPage({
  "url":"文章编辑.html",
  "generationDate":new Date(1423452567845.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"96e7a287cd9147ebbb15e1df0c283ac4",
    "type":"Axure:Page",
    "name":"文章编辑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5b66ae32915348328e8c06ebb6c0e3b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":-10,
              "y":5},
            "size":{
              "width":969,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94ab51f9a73a49b1a0dd64d4d3b8fbc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":-10,
                  "y":5},
                "size":{
                  "width":969,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u0.png"}},
{
          "id":"fec8bbf48a124a909a1b55215fa4110a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF4F4F4},
            "location":{
              "x":-1,
              "y":-41},
            "size":{
              "width":960,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40e20f15645646068196e78f6f65459b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4},
                "location":{
                  "x":-1,
                  "y":-41},
                "size":{
                  "width":960,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u2.png"}},
{
          "id":"2bea0de8a3c549b7a1e7182d171d0360",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF4F4F4},
            "location":{
              "x":0,
              "y":34},
            "size":{
              "width":117,
              "height":676},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"652e725122704c4db17c8b8d1034a0fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4},
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":117,
                  "height":676},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u4.png"}},
{
          "id":"52e712a7b61c4c66ba061e92f4d91955",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":117,
              "y":34},
            "size":{
              "width":22,
              "height":676},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d4bb35eb3b2436db6e77c5dc6fe0029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":117,
                  "y":34},
                "size":{
                  "width":22,
                  "height":676},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u6.png"}},
{
          "id":"664331768010432f9a6a503ba0776739",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFF4F4F4},
            "location":{
              "x":122,
              "y":34},
            "size":{
              "width":837,
              "height":676},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"965319ae130748c794268cbde3bd28ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4},
                "location":{
                  "x":122,
                  "y":34},
                "size":{
                  "width":837,
                  "height":676},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u8.png"}},
{
          "id":"889fc0b49d4a43008e1520742e274928",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":11,
              "y":5},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73de1aaf519d4b918b67d21e8e5a6510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":11,
                  "y":5},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7ebc3fdc8e74d188ac713e16b3f7645",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":845,
              "y":8},
            "size":{
              "width":191,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbf191e44b3d46f7948dd26cf0270561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":845,
                  "y":8},
                "size":{
                  "width":191,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5b5be0ed953447f88c1fe48f2fadcdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":159,
              "y":6},
            "size":{
              "width":158,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad4295eb53a34f03804e928a7ced2a01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":159,
                  "y":6},
                "size":{
                  "width":158,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u42.png"}},
{
          "id":"059528d7c8ac4853ac725d4bf7e18b0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":297,
              "y":7},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e5253743e9a45f99f7edb41b36bd1b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":297,
                  "y":7},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u44.png"}},
{
          "id":"159b85290b044c7cafe9b8c23e447f14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":64},
            "size":{
              "width":837,
              "height":646}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ba33748c5a34149a283ecad79324abc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":64},
                "size":{
                  "width":837,
                  "height":646}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u46.png"}},
{
          "id":"82d50f0697914dfa82b5ae5316d9a808",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":37},
            "size":{
              "width":80,
              "height":28},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f849036ef4a84df5a2bb1fe30c6bedf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":37},
                "size":{
                  "width":80,
                  "height":28},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u93.png"}},
{
          "id":"0644ca60a9f44b43a2666b93f9d5daca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":36},
            "size":{
              "width":80,
              "height":28},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2579a03d4dd842ab99753a14c84f5ea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":36},
                "size":{
                  "width":80,
                  "height":28},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时兼客/u93.png"}},
{
          "id":"3c50b5d4bc2e4001ab494f57f6ec6941",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":93},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76a100b844574eba9b897db7504d56e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":93},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6ff7f0662d64c0ab1980d15c90564a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":104},
            "size":{
              "width":761,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/待处理/u30_line.png"}},
{
          "id":"c4050577699e40cebcf58e51a4862cfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1E71B1},
            "location":{
              "x":159,
              "y":90},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6651f81fce1745008a7d9655b1a342f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1E71B1},
                "location":{
                  "x":159,
                  "y":90},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/待处理/u31.png"}},
{
          "id":"022b0a3d4b6349c993090150b08f6380",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":162,
              "y":92},
            "size":{
              "width":53,
              "height":16},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38369c6c9567495c9e273c5048d3f73e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":162,
                  "y":92},
                "size":{
                  "width":53,
                  "height":16},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4079ae8a364415798b8aa9dd7b560fb",
          "label":"menu",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":65},
            "size":{
              "width":116,
              "height":85},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72434aa45b834a5e9b096c842be4e4ca",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "size":{
                  "width":116,
                  "height":85}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8749ee74d6644946b5ceb2da5d139d4b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b484f151e7a4227a736092851b05865",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u12.png",
                    "selected~":"images/时兼客/u12_selected.png",
                    "mouseOver~":"images/时兼客/u12_mouseOver.png"}},
{
                  "id":"721b27c4183542d39615d3bdf10c6a5e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":28},
                    "size":{
                      "width":116,
                      "height":29},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4638c7c3049a42cfa157da2c1fcaaae2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":28},
                        "size":{
                          "width":116,
                          "height":29},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u14.png",
                    "selected~":"images/时兼客/u14_selected.png",
                    "mouseOver~":"images/时兼客/u14_mouseOver.png"}},
{
                  "id":"714c2697ada04f25a8bfc38fdd8be6f9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c22cf4b9acd2409a91b4c65eaea0743e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u16.png",
                    "selected~":"images/时兼客/u16_selected.png",
                    "mouseOver~":"images/时兼客/u16_mouseOver.png"}}]}]},
{
          "id":"9c87b7e61be6456192f3cb2884726b3e",
          "label":"menu",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":116,
              "height":169},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcd07c099bfa444bb33c19e2d73887d2",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "size":{
                  "width":116,
                  "height":169}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4573621c10da44379a280bbf6e281cb2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ce68e32369d44b1911a14662fa9d739",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u12.png",
                    "selected~":"images/时兼客/u12_selected.png",
                    "mouseOver~":"images/时兼客/u12_mouseOver.png"}},
{
                  "id":"7ed0b3e8b66b4a15a57c8b70a9149045",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":28},
                    "size":{
                      "width":116,
                      "height":29},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9bd64086cf14d18bc8a9e6fb4abade5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":28},
                        "size":{
                          "width":116,
                          "height":29},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u14.png",
                    "selected~":"images/时兼客/u14_selected.png",
                    "mouseOver~":"images/时兼客/u14_mouseOver.png"}},
{
                  "id":"7ccb0bf975284cb4a5f4cdeadf01129e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43c7d1d6c9964fbdb8e71d55a7c397c4",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u12.png",
                    "selected~":"images/时兼客/u12_selected.png",
                    "mouseOver~":"images/时兼客/u12_mouseOver.png"}},
{
                  "id":"274c72e9cdc74e17bc03fdb444480d11",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "location":{
                      "x":0,
                      "y":113},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0766e1b9d7f48d3b0c6a41277611829",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "location":{
                          "x":0,
                          "y":113},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/兼客管理/u22.png",
                    "selected~":"images/时兼客/u12_selected.png",
                    "mouseOver~":"images/时兼客/u12_mouseOver.png"}},
{
                  "id":"fd20cd11f26c4e68b5418c6ba19058a5",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E71B1,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "location":{
                      "x":0,
                      "y":85},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f02d001f39b4328974d20d50f3ab5f7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF1E71B1,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "location":{
                          "x":0,
                          "y":85},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/兼客管理/u22.png",
                    "selected~":"images/时兼客/u12_selected.png",
                    "mouseOver~":"images/时兼客/u12_mouseOver.png"}},
{
                  "id":"9f8e4ae1fd0e488db97d2fc7b32cb4be",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "location":{
                      "x":0,
                      "y":141},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2007409e26a94f52b57eaaea5b9fc7ec",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "location":{
                          "x":0,
                          "y":141},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/内容管理/u132.png",
                    "selected~":"images/时兼客/u16_selected.png",
                    "mouseOver~":"images/时兼客/u16_mouseOver.png"}}]}]},
{
          "id":"c3eb42ba33e6471b83014373fa1c656b",
          "label":"menu",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":380},
            "size":{
              "width":116,
              "height":113},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b943f92bfd6b4e9c87b306ea23aded71",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "size":{
                  "width":116,
                  "height":113}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"708e026da38446dc9daec261e7d75ad0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e478d0000b6c4adda38e1f0d2884693b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u12.png",
                    "selected~":"images/时兼客/u12_selected.png",
                    "mouseOver~":"images/时兼客/u12_mouseOver.png"}},
{
                  "id":"bd374eb0bc5a446ab79d6f8e42afccbb",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":28},
                    "size":{
                      "width":116,
                      "height":29},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b1b1f86ce2a491b9bbf3278f4dafebb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":28},
                        "size":{
                          "width":116,
                          "height":29},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u14.png",
                    "selected~":"images/时兼客/u14_selected.png",
                    "mouseOver~":"images/时兼客/u14_mouseOver.png"}},
{
                  "id":"257f847236904ec4b7fd5d5481c6bca1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d06a95fb79d343a983dbc02690656c2a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u12.png",
                    "selected~":"images/时兼客/u12_selected.png",
                    "mouseOver~":"images/时兼客/u12_mouseOver.png"}},
{
                  "id":"f711d9c64f234a6fb5ad6d5b2e6f8705",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF004080,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDAE0EB},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFB7C1DD}},
                      "selected":{
                        "fontWeight":"bold",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF004080},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF002346}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":85},
                    "size":{
                      "width":116,
                      "height":28},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1621c62f3fe49a58b70a928a1967aa5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF004080,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDAE0EB},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFB7C1DD}},
                          "selected":{
                            "fontWeight":"bold",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF004080},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF002346}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":85},
                        "size":{
                          "width":116,
                          "height":28},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/时兼客/u16.png",
                    "selected~":"images/时兼客/u16_selected.png",
                    "mouseOver~":"images/时兼客/u16_mouseOver.png"}}]}]},
{
          "id":"4a9e85fb19304b228fce49250df18982",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":93},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb9a681622241c6afb6b14afae844fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":93},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49eab06db5344f5aa0fc2208bb97f6e1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":656},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"898dd289949e4861a6bf46dd29d56b15",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":337},
            "size":{
              "width":670,
              "height":284}},
          "adaptiveStyles":{
}},
{
          "id":"ffba009aa9534d919b4ad79b9f895962",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":311},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"111f17f3fd4444599cbe358f662ff3a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":311},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a98257d6e7d047b9bb35170489b5ba31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":135},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4815023f21bf4789a237330cf9a7c67d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":135},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fe4316b6a7c4079baf12adfe6826ea1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":171,
              "y":201},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f61f43f09b1041a5b33036221c2983e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":171,
                  "y":201},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04e235075c934aa1ae112ec41bece9ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":168},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3620fb0e2c9c43e6a439a050f982d23b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":168},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c50eed86a7184c4794e9104b881d1b8a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":198},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"28c31ec142534a4bb63f8bd1a6bf33a9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":131},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1de2131f710a41b9891a03bbf4c6677e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":165},
            "size":{
              "width":52,
              "height":19}},
          "adaptiveStyles":{
}},
{
          "id":"8237a986866c468f8f0da097ca412892",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":236},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3172d14a9a046119e689b37dc477f92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":236},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12d9849dbbc549269043e8a38180cb20",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":238,
              "y":231.5},
            "size":{
              "width":57,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"45c46033dfb04ad2bcd53e8cc612d791",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":271},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c9e2f08561465f962b175ec78dcf82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":271},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10dc31a3ff7546b6af1a88c63ed5d2ed",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":271},
            "size":{
              "width":66,
              "height":19}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "5b66ae32915348328e8c06ebb6c0e3b0":{
      "scriptId":"u0"},
    "94ab51f9a73a49b1a0dd64d4d3b8fbc6":{
      "scriptId":"u1"},
    "fec8bbf48a124a909a1b55215fa4110a":{
      "scriptId":"u2"},
    "40e20f15645646068196e78f6f65459b":{
      "scriptId":"u3"},
    "2bea0de8a3c549b7a1e7182d171d0360":{
      "scriptId":"u4"},
    "652e725122704c4db17c8b8d1034a0fb":{
      "scriptId":"u5"},
    "52e712a7b61c4c66ba061e92f4d91955":{
      "scriptId":"u6"},
    "4d4bb35eb3b2436db6e77c5dc6fe0029":{
      "scriptId":"u7"},
    "664331768010432f9a6a503ba0776739":{
      "scriptId":"u8"},
    "965319ae130748c794268cbde3bd28ce":{
      "scriptId":"u9"},
    "889fc0b49d4a43008e1520742e274928":{
      "scriptId":"u10"},
    "73de1aaf519d4b918b67d21e8e5a6510":{
      "scriptId":"u11"},
    "c7ebc3fdc8e74d188ac713e16b3f7645":{
      "scriptId":"u12"},
    "cbf191e44b3d46f7948dd26cf0270561":{
      "scriptId":"u13"},
    "f5b5be0ed953447f88c1fe48f2fadcdb":{
      "scriptId":"u14"},
    "ad4295eb53a34f03804e928a7ced2a01":{
      "scriptId":"u15"},
    "059528d7c8ac4853ac725d4bf7e18b0d":{
      "scriptId":"u16"},
    "4e5253743e9a45f99f7edb41b36bd1b3":{
      "scriptId":"u17"},
    "159b85290b044c7cafe9b8c23e447f14":{
      "scriptId":"u18"},
    "9ba33748c5a34149a283ecad79324abc":{
      "scriptId":"u19"},
    "82d50f0697914dfa82b5ae5316d9a808":{
      "scriptId":"u20"},
    "f849036ef4a84df5a2bb1fe30c6bedf3":{
      "scriptId":"u21"},
    "0644ca60a9f44b43a2666b93f9d5daca":{
      "scriptId":"u22"},
    "2579a03d4dd842ab99753a14c84f5ea1":{
      "scriptId":"u23"},
    "3c50b5d4bc2e4001ab494f57f6ec6941":{
      "scriptId":"u24"},
    "76a100b844574eba9b897db7504d56e0":{
      "scriptId":"u25"},
    "f6ff7f0662d64c0ab1980d15c90564a8":{
      "scriptId":"u26"},
    "c4050577699e40cebcf58e51a4862cfe":{
      "scriptId":"u27"},
    "6651f81fce1745008a7d9655b1a342f5":{
      "scriptId":"u28"},
    "022b0a3d4b6349c993090150b08f6380":{
      "scriptId":"u29"},
    "38369c6c9567495c9e273c5048d3f73e":{
      "scriptId":"u30"},
    "f4079ae8a364415798b8aa9dd7b560fb":{
      "scriptId":"u31"},
    "72434aa45b834a5e9b096c842be4e4ca":{
      "scriptId":"u32"},
    "8749ee74d6644946b5ceb2da5d139d4b":{
      "scriptId":"u33"},
    "4b484f151e7a4227a736092851b05865":{
      "scriptId":"u34"},
    "721b27c4183542d39615d3bdf10c6a5e":{
      "scriptId":"u35"},
    "4638c7c3049a42cfa157da2c1fcaaae2":{
      "scriptId":"u36"},
    "714c2697ada04f25a8bfc38fdd8be6f9":{
      "scriptId":"u37"},
    "c22cf4b9acd2409a91b4c65eaea0743e":{
      "scriptId":"u38"},
    "9c87b7e61be6456192f3cb2884726b3e":{
      "scriptId":"u39"},
    "fcd07c099bfa444bb33c19e2d73887d2":{
      "scriptId":"u40"},
    "4573621c10da44379a280bbf6e281cb2":{
      "scriptId":"u41"},
    "7ce68e32369d44b1911a14662fa9d739":{
      "scriptId":"u42"},
    "7ed0b3e8b66b4a15a57c8b70a9149045":{
      "scriptId":"u43"},
    "d9bd64086cf14d18bc8a9e6fb4abade5":{
      "scriptId":"u44"},
    "7ccb0bf975284cb4a5f4cdeadf01129e":{
      "scriptId":"u45"},
    "43c7d1d6c9964fbdb8e71d55a7c397c4":{
      "scriptId":"u46"},
    "fd20cd11f26c4e68b5418c6ba19058a5":{
      "scriptId":"u47"},
    "7f02d001f39b4328974d20d50f3ab5f7":{
      "scriptId":"u48"},
    "274c72e9cdc74e17bc03fdb444480d11":{
      "scriptId":"u49"},
    "a0766e1b9d7f48d3b0c6a41277611829":{
      "scriptId":"u50"},
    "9f8e4ae1fd0e488db97d2fc7b32cb4be":{
      "scriptId":"u51"},
    "2007409e26a94f52b57eaaea5b9fc7ec":{
      "scriptId":"u52"},
    "c3eb42ba33e6471b83014373fa1c656b":{
      "scriptId":"u53"},
    "b943f92bfd6b4e9c87b306ea23aded71":{
      "scriptId":"u54"},
    "708e026da38446dc9daec261e7d75ad0":{
      "scriptId":"u55"},
    "e478d0000b6c4adda38e1f0d2884693b":{
      "scriptId":"u56"},
    "bd374eb0bc5a446ab79d6f8e42afccbb":{
      "scriptId":"u57"},
    "5b1b1f86ce2a491b9bbf3278f4dafebb":{
      "scriptId":"u58"},
    "257f847236904ec4b7fd5d5481c6bca1":{
      "scriptId":"u59"},
    "d06a95fb79d343a983dbc02690656c2a":{
      "scriptId":"u60"},
    "f711d9c64f234a6fb5ad6d5b2e6f8705":{
      "scriptId":"u61"},
    "b1621c62f3fe49a58b70a928a1967aa5":{
      "scriptId":"u62"},
    "4a9e85fb19304b228fce49250df18982":{
      "scriptId":"u63"},
    "4fb9a681622241c6afb6b14afae844fc":{
      "scriptId":"u64"},
    "49eab06db5344f5aa0fc2208bb97f6e1":{
      "scriptId":"u65"},
    "898dd289949e4861a6bf46dd29d56b15":{
      "scriptId":"u66"},
    "ffba009aa9534d919b4ad79b9f895962":{
      "scriptId":"u67"},
    "111f17f3fd4444599cbe358f662ff3a5":{
      "scriptId":"u68"},
    "a98257d6e7d047b9bb35170489b5ba31":{
      "scriptId":"u69"},
    "4815023f21bf4789a237330cf9a7c67d":{
      "scriptId":"u70"},
    "6fe4316b6a7c4079baf12adfe6826ea1":{
      "scriptId":"u71"},
    "f61f43f09b1041a5b33036221c2983e7":{
      "scriptId":"u72"},
    "04e235075c934aa1ae112ec41bece9ec":{
      "scriptId":"u73"},
    "3620fb0e2c9c43e6a439a050f982d23b":{
      "scriptId":"u74"},
    "c50eed86a7184c4794e9104b881d1b8a":{
      "scriptId":"u75"},
    "28c31ec142534a4bb63f8bd1a6bf33a9":{
      "scriptId":"u76"},
    "1de2131f710a41b9891a03bbf4c6677e":{
      "scriptId":"u77"},
    "8237a986866c468f8f0da097ca412892":{
      "scriptId":"u78"},
    "a3172d14a9a046119e689b37dc477f92":{
      "scriptId":"u79"},
    "12d9849dbbc549269043e8a38180cb20":{
      "scriptId":"u80"},
    "45c46033dfb04ad2bcd53e8cc612d791":{
      "scriptId":"u81"},
    "76c9e2f08561465f962b175ec78dcf82":{
      "scriptId":"u82"},
    "10dc31a3ff7546b6af1a88c63ed5d2ed":{
      "scriptId":"u83"}}});