$axure.loadCurrentPage({
  "url":"发工资页（已有兼客报名情况）.html",
  "generationDate":new Date(1463126099300.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"05408a7c9f2a4a69af9bdc0214f80918",
    "type":"Axure:Page",
    "name":"发工资页（已有兼客报名情况）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9bd6e36a1b274a3a96475ff7de61e4c1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"3447add0283d4746843bc0c3f25760c6"},
{
          "id":"e4ac74a9a35c46e7a5632a88ebf74434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":125},
            "size":{
              "width":808,
              "height":625},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dbfec650814428f8eded4f06f47acfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":224,
                  "y":125},
                "size":{
                  "width":808,
                  "height":625},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代发工资-首页/u21.png"}},
{
          "id":"fae4a066432c4c928df2a674e8497454",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":191},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/发工资页/u29_line.png"}},
{
          "id":"9dddd8b710844419b09589d6698ac22a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":270},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/发工资页/u29_line.png"}},
{
          "id":"593c7329e63d48fe8748e2405169bfb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B7C9C,
              "opacity":1},
            "location":{
              "x":272,
              "y":233},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a7282f2abb840f5b29e461605b5e734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C,
                  "opacity":1},
                "location":{
                  "x":272,
                  "y":233},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3691bb784bd47a09ad8d1a96b7d3e40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":403,
              "y":233},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe2f1b886dd4a72a592d751377d4849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":403,
                  "y":233},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27a9d3cb5395439b829eaa9eba0c4bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":260,
              "y":157},
            "size":{
              "width":181,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3506ac93f9e4ab5a80b87ba7439abd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":260,
                  "y":157},
                "size":{
                  "width":181,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf87468c3bb94decbed233a3b4b2c34c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":287,
              "y":264},
            "size":{
              "width":18,
              "height":11},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e84655f9cec465d93864616417cc1e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":287,
                  "y":264},
                "size":{
                  "width":18,
                  "height":11},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资页/u39.png"}},
{
          "id":"f811466856a0440989f1ea8b3d686142",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":260,
              "y":290},
            "size":{
              "width":94,
              "height":31},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ea1a32a159d476184bfb3fe190f0490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":260,
                  "y":290},
                "size":{
                  "width":94,
                  "height":31},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏元件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u46.png"}},
{
          "id":"3d413ae5025549b0a9fcf9016af94999",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":363,
              "y":299},
            "size":{
              "width":167,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b257031c52a24a29bc32643da9630a6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":363,
                  "y":299},
                "size":{
                  "width":167,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca0c610123dc429884e5f7fc15f6f1d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":833,
              "y":600},
            "size":{
              "width":130,
              "height":42},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df5e0be1c844f7fb0e28dc593ef228a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":833,
                  "y":600},
                "size":{
                  "width":130,
                  "height":42},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏元件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u36.png"}},
{
          "id":"9fa525a0121943bc9c518c9284d57c7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":626,
              "y":514},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"780f55ac16eb4f8db95ba928f7f7a3da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":626,
                  "y":514},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d61c34cbcab84b20ba8dcccba07766e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":868,
              "y":514},
            "size":{
              "width":95,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6a7122e35bf43cb941a55fbf206cd09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":868,
                  "y":514},
                "size":{
                  "width":95,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e54d2552217a48ccbc895661ca9f654f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":759,
              "y":514},
            "size":{
              "width":26,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a90e62d21bc5435c9a3151a8f12b51ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":759,
                  "y":514},
                "size":{
                  "width":26,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d633d41c86a54541ba3283add6f3fadb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":797,
              "y":660},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"580c0a70569b46a1a015093035608e8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":797,
                  "y":660},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17bfcf7e2ffe4e3691ee716eba11645c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":510},
            "size":{
              "width":62,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3648948d746481fbf354e1bbf1062d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":510},
                "size":{
                  "width":62,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u110.png"}},
{
          "id":"407c1d1b8a8d4bd886e8b22e2dd702d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":510},
            "size":{
              "width":62,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b20c6ad70e44f658f8acc24cf7c18cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":510},
                "size":{
                  "width":62,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u110.png"}},
{
          "id":"dea53478256e4bbc8ec3f58662233689",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":447},
            "size":{
              "width":70,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ac58e7e36604c38b90a951c2cbad798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":880,
                  "y":447},
                "size":{
                  "width":70,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u54.png"}},
{
          "id":"4088843f9b6547b0af96d83b93b99828",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":401},
            "size":{
              "width":70,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a7e461aae354c06b3cfab061a64bcdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":880,
                  "y":401},
                "size":{
                  "width":70,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u54.png"}},
{
          "id":"d74b18271b9c4180b0c6deeadd2289d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":357},
            "size":{
              "width":70,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7f1fd404fe24bf88e1a7d207aeaf7d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":880,
                  "y":357},
                "size":{
                  "width":70,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u54.png"}},
{
          "id":"db43ff6ed2f44a99a769c563f78664a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":379,
              "y":362},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cd62c3c9f0948139e3a86c5cc19a70a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":379,
                  "y":362},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74c4d4851b384b829f9c1af21f6b9db8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":571,
              "y":362},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cae6d2e0d96e47e2ae01a148f51ae737",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":571,
                  "y":362},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f847784b6a24c509d1fab41fb59e42c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":862,
              "y":363},
            "size":{
              "width":69,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6c17838b7764d0daecd715a16953be6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":862,
                  "y":363},
                "size":{
                  "width":69,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee183e30c88447109ee77228771d064c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":378,
              "y":407},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f7a30a2e8e24db081d7770601e68076",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":378,
                  "y":407},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4bb863789944712bc71b501fd3ae1f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":571,
              "y":407},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4a5d78b23704cb18b02cbc349074ed4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":571,
                  "y":407},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f838f03ad334f4592e52826676d8a8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":379,
              "y":452},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd2b6f5bb3bc46ac8d8ae2c855dc7627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":379,
                  "y":452},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e2ef207a33d4e9aa7fa81d6ab536a7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":572,
              "y":452},
            "size":{
              "width":99,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a23e5a5184ba4f9f8e021b3ebf961f54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":572,
                  "y":452},
                "size":{
                  "width":99,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b352846f3ad646a0bc818f2166551058",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":380,
              "y":328},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bcb34d22dd941e48a1e18490d5bf179",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":380,
                  "y":328},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c6260b062bd494495f29336bff91ecb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":586,
              "y":326},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f24882ef2a08461f842fb15fb5029d90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":586,
                  "y":326},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e22af7eb83484227bfc5a84f6bc4290c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":877,
              "y":326},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3f6bf3a87d742a7a6229f6cffaf13d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":877,
                  "y":326},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"158c2374dfef4cb5a516d778589b418d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":357},
            "size":{
              "width":22,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b91e67bd3eb34c1894b214c72acc0968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":357},
                "size":{
                  "width":22,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u98.png"}},
{
          "id":"e09a4ac3e773490aa05b2fa087299368",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":404.5},
            "size":{
              "width":22,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9962d6f185d04595b95bc48869409b55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":404.5},
                "size":{
                  "width":22,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u98.png"}},
{
          "id":"a59d5bb4f5e846f9acea136a528713b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":452},
            "size":{
              "width":22,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46d4bab069a248b29b257281480cad4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":452},
                "size":{
                  "width":22,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u98.png"}},
{
          "id":"8c26e4539b454668bef541ac0a7433de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":862,
              "y":407},
            "size":{
              "width":69,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"727bc4622272479a8f62ae6349133786",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":862,
                  "y":407},
                "size":{
                  "width":69,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98070e10a93144dd9226db8b2b57aff3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":862,
              "y":453},
            "size":{
              "width":69,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55b58c1247494df89757115f11106571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":862,
                  "y":453},
                "size":{
                  "width":69,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79f3344ff48246a38173edfed72718c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":729,
              "y":363},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"733e277154c04cd6985fd9560d916a5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":729,
                  "y":363},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d65e3879661a453896989e184b739349",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":729,
              "y":407},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60d9e6e110be4395b313a64d1d28c17e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":729,
                  "y":407},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a7e29e992b047949bd0a81cc7eebf9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":729,
              "y":453},
            "size":{
              "width":61,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e8772d75f1d40e08385c774c4ca0971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":729,
                  "y":453},
                "size":{
                  "width":61,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08b68383c3c6438ead2d1ad218463fdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":734,
              "y":326},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa6c89ce21a149b2aa854ffeec6e14b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":734,
                  "y":326},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"438d4a0255324c99a93b5ef6b0c5c3aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":313,
              "y":360},
            "size":{
              "width":56,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF008000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79cae45d81c4632a43c0319f5e320c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":313,
                  "y":360},
                "size":{
                  "width":56,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF008000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u138.png"}},
{
          "id":"38f77f97c0ed485b94f75175a5206970",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":438,
              "y":357},
            "size":{
              "width":22,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d11f97502ff48588e7fcfdb34851235",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":357},
                "size":{
                  "width":22,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33ba5de98289423491f69fb78f6aecef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":438,
              "y":446},
            "size":{
              "width":22,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56a28751424445a0b656e6d6521250d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":446},
                "size":{
                  "width":22,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d0ad9bf5846455da8685a6a28a7566e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":478,
              "y":362},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd048d9b841e436d946ffe267c1247fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":478,
                  "y":362},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33cbf637b9304c51b79120acfe03d172",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":477,
              "y":407},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e31998c4ba954f82b8ea75360224dc4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":477,
                  "y":407},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87fe07db763e45c392b1e2b5a1e3e6b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":478,
              "y":452},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f6a2b0e78a44d17b7faa729aaa38f24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":478,
                  "y":452},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"663a817bb68346a58eb6510f5e98207c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":479,
              "y":328},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f491f9eee7342e8bc1703b2539200e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":479,
                  "y":328},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2154c778a4143a3aec083d64b742593",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":310,
              "y":453},
            "size":{
              "width":58,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81354d47441b4106a0176a10d93dfb37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":453},
                "size":{
                  "width":58,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u140.png"}},
{
          "id":"94052d36ac0c49e7bf58a70348717082",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":313,
              "y":408},
            "size":{
              "width":56,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF008000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd5be7399fea42af812cb692871c4e8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":313,
                  "y":408},
                "size":{
                  "width":56,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF008000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发工资-已有兼客（导入成功）/u138.png"}},
{
          "id":"60110304879a4374862214a5be28682c",
          "label":"导入工资表",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":1,
              "y":86},
            "size":{
              "width":1074,
              "height":697},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"da87b299d5f54c15963788ac3ff3b01b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d6c833af64dd41c9b229aade18a9d068",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "location":{
                      "x":-1,
                      "y":-1},
                    "size":{
                      "width":1080,
                      "height":710},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48e015111f354c5286a4766382997183",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.3",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "location":{
                          "x":-1,
                          "y":-1},
                        "size":{
                          "width":1080,
                          "height":710},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发工资页/u50.png"}},
{
                  "id":"cb6a3f4c633745c4beba774a7eae5161",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":296,
                      "y":80},
                    "size":{
                      "width":624,
                      "height":465}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15af7292dea84ad89395f9e7ec18c70f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":296,
                          "y":80},
                        "size":{
                          "width":624,
                          "height":465}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发工资页/u52.png"}},
{
                  "id":"8113eb01a8044b8c96a6690feea08f89",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":885,
                      "y":83},
                    "size":{
                      "width":30,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 导入工资表",
                              "objectsToFades":[{
                                  "objectPath":["60110304879a4374862214a5be28682c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"a672f8416c754a8b8ef97afa270d5703",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":818,
                      "y":508},
                    "size":{
                      "width":82,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 导入工资表",
                              "objectsToFades":[{
                                  "objectPath":["60110304879a4374862214a5be28682c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"9ea97dd27cdf465293e29f92b3a2a244",
                  "label":"",
                  "parentDynamicPanel":"60110304879a4374862214a5be28682c",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":715,
                      "y":508},
                    "size":{
                      "width":82,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 发工资-已有兼客（导入成功）",
                              "target":{
                                "targetType":"page",
                                "url":"发工资-已有兼客（导入成功）.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]}]}},
  "masters":{
    "3447add0283d4746843bc0c3f25760c6":{
      "packageId":"3447add0283d4746843bc0c3f25760c6",
      "type":"Axure:Master",
      "name":"代发工资WEB模板",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3025823a927649149200c8f411c1f28f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "size":{
                "width":1074,
                "height":866},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0f8efe15b78146569b1dfecaad969e66",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "size":{
                    "width":1074,
                    "height":866},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u1.png"}},
{
            "id":"b459e592af584004a8fa437f80619926",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":128},
              "size":{
                "width":170,
                "height":388}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2e2ed2e3bff144219f7490def1c1a7b1",
                "label":"",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "size":{
                    "width":170,
                    "height":388}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"6001ead4bb154f6b9678fbeeccc6f0ac",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "fontSize":"14px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":170,
                        "height":57}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"89ab1feb32b54ce09c97920125bdf1c3",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"14px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":170,
                            "height":57}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u5.png"}},
{
                    "id":"612210abc25140d690a0b8331be2a679",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":57},
                      "size":{
                        "width":170,
                        "height":56}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"98cc0b8c4ecc4afa9040f147a4d7fe59",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":57},
                          "size":{
                            "width":170,
                            "height":56}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u7.png"}},
{
                    "id":"fc9b7468e8c148dab667dc84b8a86413",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":113},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2f7e94d6b3eb4e63b2e0d9d5d1d2c836",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":113},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u9.png"}},
{
                    "id":"81fddc2c676346b3a7a4bc2392f806fb",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":168},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2476e6aba3eb45a5a221a1ebce5ecef8",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":168},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u9.png"}},
{
                    "id":"340ef66b12ac410ea87bb2abd152f41c",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":278},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3b9c76c38ae345819394c93eb2ed9503",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":278},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u9.png"}},
{
                    "id":"25878244aaad4e248693071b2e9cd7dc",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":333},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c31c192645b54426b719e87e667e6a3e",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":333},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u17.png"}},
{
                    "id":"44e2ca1a92e64cf5ab89e6ec0ddefaae",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":0,
                        "y":223},
                      "size":{
                        "width":170,
                        "height":55}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"02a0e4ebb9464cfeaad5ee7fcb38c1e7",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":0,
                            "y":223},
                          "size":{
                            "width":170,
                            "height":55}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/代发工资-首页/u9.png"}}]}]},
{
            "id":"550f9ab3a7b24ac094bec0816ab7ffd1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF6B7C9C},
              "location":{
                "x":31.5,
                "y":460},
              "size":{
                "width":183,
                "height":60},
              "cornerRadiusTopLeft":"3",
              "outerShadow":{
                "on":true,
                "offsetX":0,
                "offsetY":5,
                "blurRadius":5,
                "color":{
                  "r":0,
                  "g":0,
                  "b":0,
                  "a":0.137254901960784}}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58f22461c7ca4c7aa7fcd6559bf47ac6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF6B7C9C},
                  "location":{
                    "x":31.5,
                    "y":460},
                  "size":{
                    "width":183,
                    "height":60},
                  "cornerRadiusTopLeft":"3",
                  "outerShadow":{
                    "on":true,
                    "offsetX":0,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.137254901960784}}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u19.png"}},
{
            "id":"015c8e27a78d4fa79c2de220ae6e5890",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":224,
                "y":125},
              "size":{
                "width":808,
                "height":625},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "cornerRadiusTopLeft":"8"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d48724a8dcde4164b4d26a45707e6018",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":224,
                    "y":125},
                  "size":{
                    "width":808,
                    "height":625},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "cornerRadiusTopLeft":"8"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u21.png"}},
{
            "id":"7799fd4ee3c44f7b8473cd01e491f940",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF6B7C9C},
              "location":{
                "x":0,
                "y":783},
              "size":{
                "width":1074,
                "height":83}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cceb82e3e99d40f8a2ffca63f4e3fe0a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF6B7C9C},
                  "location":{
                    "x":0,
                    "y":783},
                  "size":{
                    "width":1074,
                    "height":83}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u23.png"}},
{
            "id":"4f89b782091b438aae6fe48d6a4a392e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF6B7C9C},
              "size":{
                "width":1074,
                "height":86}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35f376c828d24457b6e3475eaee164a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF6B7C9C},
                  "size":{
                    "width":1074,
                    "height":86}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/代发工资-首页/u25.png"}}]}}},
  "objectPaths":{
    "9bd6e36a1b274a3a96475ff7de61e4c1":{
      "scriptId":"u0",
      "3025823a927649149200c8f411c1f28f":{
        "scriptId":"u1"},
      "0f8efe15b78146569b1dfecaad969e66":{
        "scriptId":"u2"},
      "b459e592af584004a8fa437f80619926":{
        "scriptId":"u3"},
      "2e2ed2e3bff144219f7490def1c1a7b1":{
        "scriptId":"u4"},
      "6001ead4bb154f6b9678fbeeccc6f0ac":{
        "scriptId":"u5"},
      "89ab1feb32b54ce09c97920125bdf1c3":{
        "scriptId":"u6"},
      "612210abc25140d690a0b8331be2a679":{
        "scriptId":"u7"},
      "98cc0b8c4ecc4afa9040f147a4d7fe59":{
        "scriptId":"u8"},
      "fc9b7468e8c148dab667dc84b8a86413":{
        "scriptId":"u9"},
      "2f7e94d6b3eb4e63b2e0d9d5d1d2c836":{
        "scriptId":"u10"},
      "81fddc2c676346b3a7a4bc2392f806fb":{
        "scriptId":"u11"},
      "2476e6aba3eb45a5a221a1ebce5ecef8":{
        "scriptId":"u12"},
      "44e2ca1a92e64cf5ab89e6ec0ddefaae":{
        "scriptId":"u13"},
      "02a0e4ebb9464cfeaad5ee7fcb38c1e7":{
        "scriptId":"u14"},
      "340ef66b12ac410ea87bb2abd152f41c":{
        "scriptId":"u15"},
      "3b9c76c38ae345819394c93eb2ed9503":{
        "scriptId":"u16"},
      "25878244aaad4e248693071b2e9cd7dc":{
        "scriptId":"u17"},
      "c31c192645b54426b719e87e667e6a3e":{
        "scriptId":"u18"},
      "550f9ab3a7b24ac094bec0816ab7ffd1":{
        "scriptId":"u19"},
      "58f22461c7ca4c7aa7fcd6559bf47ac6":{
        "scriptId":"u20"},
      "015c8e27a78d4fa79c2de220ae6e5890":{
        "scriptId":"u21"},
      "d48724a8dcde4164b4d26a45707e6018":{
        "scriptId":"u22"},
      "7799fd4ee3c44f7b8473cd01e491f940":{
        "scriptId":"u23"},
      "cceb82e3e99d40f8a2ffca63f4e3fe0a":{
        "scriptId":"u24"},
      "4f89b782091b438aae6fe48d6a4a392e":{
        "scriptId":"u25"},
      "35f376c828d24457b6e3475eaee164a4":{
        "scriptId":"u26"}},
    "e4ac74a9a35c46e7a5632a88ebf74434":{
      "scriptId":"u27"},
    "4dbfec650814428f8eded4f06f47acfc":{
      "scriptId":"u28"},
    "fae4a066432c4c928df2a674e8497454":{
      "scriptId":"u29"},
    "9dddd8b710844419b09589d6698ac22a":{
      "scriptId":"u30"},
    "593c7329e63d48fe8748e2405169bfb5":{
      "scriptId":"u31"},
    "2a7282f2abb840f5b29e461605b5e734":{
      "scriptId":"u32"},
    "a3691bb784bd47a09ad8d1a96b7d3e40":{
      "scriptId":"u33"},
    "6fe2f1b886dd4a72a592d751377d4849":{
      "scriptId":"u34"},
    "27a9d3cb5395439b829eaa9eba0c4bb7":{
      "scriptId":"u35"},
    "a3506ac93f9e4ab5a80b87ba7439abd3":{
      "scriptId":"u36"},
    "bf87468c3bb94decbed233a3b4b2c34c":{
      "scriptId":"u37"},
    "5e84655f9cec465d93864616417cc1e4":{
      "scriptId":"u38"},
    "f811466856a0440989f1ea8b3d686142":{
      "scriptId":"u39"},
    "8ea1a32a159d476184bfb3fe190f0490":{
      "scriptId":"u40"},
    "3d413ae5025549b0a9fcf9016af94999":{
      "scriptId":"u41"},
    "b257031c52a24a29bc32643da9630a6b":{
      "scriptId":"u42"},
    "ca0c610123dc429884e5f7fc15f6f1d2":{
      "scriptId":"u43"},
    "8df5e0be1c844f7fb0e28dc593ef228a":{
      "scriptId":"u44"},
    "9fa525a0121943bc9c518c9284d57c7f":{
      "scriptId":"u45"},
    "780f55ac16eb4f8db95ba928f7f7a3da":{
      "scriptId":"u46"},
    "d61c34cbcab84b20ba8dcccba07766e1":{
      "scriptId":"u47"},
    "b6a7122e35bf43cb941a55fbf206cd09":{
      "scriptId":"u48"},
    "e54d2552217a48ccbc895661ca9f654f":{
      "scriptId":"u49"},
    "a90e62d21bc5435c9a3151a8f12b51ee":{
      "scriptId":"u50"},
    "d633d41c86a54541ba3283add6f3fadb":{
      "scriptId":"u51"},
    "580c0a70569b46a1a015093035608e8d":{
      "scriptId":"u52"},
    "17bfcf7e2ffe4e3691ee716eba11645c":{
      "scriptId":"u53"},
    "c3648948d746481fbf354e1bbf1062d9":{
      "scriptId":"u54"},
    "407c1d1b8a8d4bd886e8b22e2dd702d1":{
      "scriptId":"u55"},
    "0b20c6ad70e44f658f8acc24cf7c18cb":{
      "scriptId":"u56"},
    "dea53478256e4bbc8ec3f58662233689":{
      "scriptId":"u57"},
    "7ac58e7e36604c38b90a951c2cbad798":{
      "scriptId":"u58"},
    "4088843f9b6547b0af96d83b93b99828":{
      "scriptId":"u59"},
    "4a7e461aae354c06b3cfab061a64bcdf":{
      "scriptId":"u60"},
    "d74b18271b9c4180b0c6deeadd2289d4":{
      "scriptId":"u61"},
    "b7f1fd404fe24bf88e1a7d207aeaf7d9":{
      "scriptId":"u62"},
    "db43ff6ed2f44a99a769c563f78664a0":{
      "scriptId":"u63"},
    "3cd62c3c9f0948139e3a86c5cc19a70a":{
      "scriptId":"u64"},
    "74c4d4851b384b829f9c1af21f6b9db8":{
      "scriptId":"u65"},
    "cae6d2e0d96e47e2ae01a148f51ae737":{
      "scriptId":"u66"},
    "9f847784b6a24c509d1fab41fb59e42c":{
      "scriptId":"u67"},
    "d6c17838b7764d0daecd715a16953be6":{
      "scriptId":"u68"},
    "ee183e30c88447109ee77228771d064c":{
      "scriptId":"u69"},
    "8f7a30a2e8e24db081d7770601e68076":{
      "scriptId":"u70"},
    "f4bb863789944712bc71b501fd3ae1f5":{
      "scriptId":"u71"},
    "c4a5d78b23704cb18b02cbc349074ed4":{
      "scriptId":"u72"},
    "6f838f03ad334f4592e52826676d8a8c":{
      "scriptId":"u73"},
    "dd2b6f5bb3bc46ac8d8ae2c855dc7627":{
      "scriptId":"u74"},
    "8e2ef207a33d4e9aa7fa81d6ab536a7f":{
      "scriptId":"u75"},
    "a23e5a5184ba4f9f8e021b3ebf961f54":{
      "scriptId":"u76"},
    "b352846f3ad646a0bc818f2166551058":{
      "scriptId":"u77"},
    "3bcb34d22dd941e48a1e18490d5bf179":{
      "scriptId":"u78"},
    "9c6260b062bd494495f29336bff91ecb":{
      "scriptId":"u79"},
    "f24882ef2a08461f842fb15fb5029d90":{
      "scriptId":"u80"},
    "e22af7eb83484227bfc5a84f6bc4290c":{
      "scriptId":"u81"},
    "a3f6bf3a87d742a7a6229f6cffaf13d3":{
      "scriptId":"u82"},
    "158c2374dfef4cb5a516d778589b418d":{
      "scriptId":"u83"},
    "b91e67bd3eb34c1894b214c72acc0968":{
      "scriptId":"u84"},
    "e09a4ac3e773490aa05b2fa087299368":{
      "scriptId":"u85"},
    "9962d6f185d04595b95bc48869409b55":{
      "scriptId":"u86"},
    "a59d5bb4f5e846f9acea136a528713b2":{
      "scriptId":"u87"},
    "46d4bab069a248b29b257281480cad4b":{
      "scriptId":"u88"},
    "8c26e4539b454668bef541ac0a7433de":{
      "scriptId":"u89"},
    "727bc4622272479a8f62ae6349133786":{
      "scriptId":"u90"},
    "98070e10a93144dd9226db8b2b57aff3":{
      "scriptId":"u91"},
    "55b58c1247494df89757115f11106571":{
      "scriptId":"u92"},
    "79f3344ff48246a38173edfed72718c0":{
      "scriptId":"u93"},
    "733e277154c04cd6985fd9560d916a5d":{
      "scriptId":"u94"},
    "d65e3879661a453896989e184b739349":{
      "scriptId":"u95"},
    "60d9e6e110be4395b313a64d1d28c17e":{
      "scriptId":"u96"},
    "2a7e29e992b047949bd0a81cc7eebf9c":{
      "scriptId":"u97"},
    "4e8772d75f1d40e08385c774c4ca0971":{
      "scriptId":"u98"},
    "08b68383c3c6438ead2d1ad218463fdc":{
      "scriptId":"u99"},
    "aa6c89ce21a149b2aa854ffeec6e14b3":{
      "scriptId":"u100"},
    "438d4a0255324c99a93b5ef6b0c5c3aa":{
      "scriptId":"u101"},
    "b79cae45d81c4632a43c0319f5e320c7":{
      "scriptId":"u102"},
    "38f77f97c0ed485b94f75175a5206970":{
      "scriptId":"u103"},
    "6d11f97502ff48588e7fcfdb34851235":{
      "scriptId":"u104"},
    "33ba5de98289423491f69fb78f6aecef":{
      "scriptId":"u105"},
    "56a28751424445a0b656e6d6521250d3":{
      "scriptId":"u106"},
    "6d0ad9bf5846455da8685a6a28a7566e":{
      "scriptId":"u107"},
    "fd048d9b841e436d946ffe267c1247fd":{
      "scriptId":"u108"},
    "33cbf637b9304c51b79120acfe03d172":{
      "scriptId":"u109"},
    "e31998c4ba954f82b8ea75360224dc4c":{
      "scriptId":"u110"},
    "87fe07db763e45c392b1e2b5a1e3e6b8":{
      "scriptId":"u111"},
    "3f6a2b0e78a44d17b7faa729aaa38f24":{
      "scriptId":"u112"},
    "663a817bb68346a58eb6510f5e98207c":{
      "scriptId":"u113"},
    "2f491f9eee7342e8bc1703b2539200e0":{
      "scriptId":"u114"},
    "b2154c778a4143a3aec083d64b742593":{
      "scriptId":"u115"},
    "81354d47441b4106a0176a10d93dfb37":{
      "scriptId":"u116"},
    "94052d36ac0c49e7bf58a70348717082":{
      "scriptId":"u117"},
    "bd5be7399fea42af812cb692871c4e8e":{
      "scriptId":"u118"},
    "60110304879a4374862214a5be28682c":{
      "scriptId":"u119"},
    "d6c833af64dd41c9b229aade18a9d068":{
      "scriptId":"u120"},
    "48e015111f354c5286a4766382997183":{
      "scriptId":"u121"},
    "cb6a3f4c633745c4beba774a7eae5161":{
      "scriptId":"u122"},
    "15af7292dea84ad89395f9e7ec18c70f":{
      "scriptId":"u123"},
    "8113eb01a8044b8c96a6690feea08f89":{
      "scriptId":"u124"},
    "a672f8416c754a8b8ef97afa270d5703":{
      "scriptId":"u125"},
    "9ea97dd27cdf465293e29f92b3a2a244":{
      "scriptId":"u126"}}});