$axure.loadCurrentPage({
  "url":"点名记录.html",
  "generationDate":new Date(1468320337348.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c2bb3e9de6e84206a07f9508030d2112",
    "type":"Axure:Page",
    "name":"点名记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"901e3164b9194d94abbf0cd7a97eea88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "size":{
              "width":1074,
              "height":866},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b5db1e072c4059929d6938b372fbb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":1074,
                  "height":866},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/岗位管理/u6.png"}},
{
          "id":"969aba5ac8834a0ba97db685a70fd36f",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":128},
            "size":{
              "width":170,
              "height":223}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9eb59b31d2a4851af3e45a9b02f1762",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":170,
                  "height":223}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb5a4c6b9b2547c3b1a73b186fc7bf8c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":170,
                      "height":57}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8884cdea0cd477c8162df9f69dfcece",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":170,
                          "height":57}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/岗位管理/u10.png"}},
{
                  "id":"7de40b2b3f0643a7b773fc99409a5312",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":170,
                      "height":56}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f082a500e5b4bbb8178d525bf842540",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":57},
                        "size":{
                          "width":170,
                          "height":56}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/岗位管理/u12.png"}},
{
                  "id":"cd235d8b50db46258d05c75434641636",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":113},
                    "size":{
                      "width":170,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"628c42deba6c4cbf97359258a80d3a29",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":113},
                        "size":{
                          "width":170,
                          "height":55}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/岗位管理/u14.png"}},
{
                  "id":"a12244bbfc4f461c8ae2771ef667994b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":168},
                    "size":{
                      "width":170,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3411813979f0414196d83ccb91673240",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":168},
                        "size":{
                          "width":170,
                          "height":55}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/岗位管理/u20.png"}}]}]},
{
          "id":"021bc7671d41454d93dff979c63e20d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":31,
              "y":125},
            "size":{
              "width":183,
              "height":60},
            "cornerRadiusTopLeft":"3",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.137254901960784}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eda180b97db4c939d8f24f192db3121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":31,
                  "y":125},
                "size":{
                  "width":183,
                  "height":60},
                "cornerRadiusTopLeft":"3",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.137254901960784}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/岗位管理/u22.png"}},
{
          "id":"6dc785763ad5454085d1d1efa4d464bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":125},
            "size":{
              "width":808,
              "height":625},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"063f47758c2740389c482d65893025d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":224,
                  "y":125},
                "size":{
                  "width":808,
                  "height":625},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/岗位管理/u24.png"}},
{
          "id":"c4add9095a2e45d6907380c4368b6b83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "location":{
              "x":0,
              "y":783},
            "size":{
              "width":1074,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"730a90dca7d34d4cb85546a4161df34d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "location":{
                  "x":0,
                  "y":783},
                "size":{
                  "width":1074,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/岗位管理/u26.png"}},
{
          "id":"0c6767c99d7a4314a008670130f597b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF6B7C9C},
            "size":{
              "width":1074,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2ba793ba99d4c9ebaa57eda63dbe334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B7C9C},
                "size":{
                  "width":1074,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/岗位管理/u28.png"}},
{
          "id":"a0baf79f0a0e44cab22ff8f6cc427576",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CCFF,
              "opacity":1},
            "location":{
              "x":240,
              "y":138},
            "size":{
              "width":79,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d50690fd1ef249fa95e011d0530b525e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":138},
                "size":{
                  "width":79,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7d09bed55ab4d4daefeabb8ce17104b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CCFF,
              "opacity":1},
            "location":{
              "x":319,
              "y":137},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5f1ae2bdb95408fa8154989c99222ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF,
                  "opacity":1},
                "location":{
                  "x":319,
                  "y":137},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61507530ab9249d3ad8182c4ddced087",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":167},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/岗位管理/u47_line.png"}},
{
          "id":"f23548b5e40f4ecda8364a3e5ec001c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":407,
              "y":137},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ffdd7739aa045978d9d763449faf948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":407,
                  "y":137},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"429a767c107f42f5a69ff840b83a8820",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":396,
              "y":137},
            "size":{
              "width":7,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"477547bc32004e2bbfc56f5eacfd057d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":396,
                  "y":137},
                "size":{
                  "width":7,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14dc4e6a1a324468b566ee026cfb6d4b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":202},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/岗位管理/u47_line.png"}},
{
          "id":"44993853252d4065a67e493df92a2811",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":282,
              "y":179},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d49830f741f4071a75c5609ae110ef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":282,
                  "y":179},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"243030f4bf3a46fc9c03fa772ce89aa0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":400,
              "y":179},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"764e618774d24ec9b974bfdca7f5f3e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":400,
                  "y":179},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1497c348ce8d46c9bf6b5aee722757c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":544,
              "y":179},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e21cd5a73fc4a44949bd47a15ca3b3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":544,
                  "y":179},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"063626df56224cb7a0f9d9bd163090b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":695,
              "y":179},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edf1475813404c42b5154b50e88c2b21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":695,
                  "y":179},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53c09d30c14b43dbaa3e7801c4efc682",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":220},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6a4b2bc99f4c8e848ea285378baa1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":220},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de152dc4546c4afba3c722ec312bc8e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":260},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"717d2e9407e74821aa93753f6e4bca1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":260},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5635fbd9bea47c6bad2417e337b39aa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":244},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/岗位管理/u47_line.png"}},
{
          "id":"b5268c316ee242abbb27e68a0273c2d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":283},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/岗位管理/u47_line.png"}},
{
          "id":"5f4001b8930144d2992b0d3beb6eb241",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":300},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39e6a3534d454e9080d1fbb55d511bd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":300},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11285706eda44597a819165e979e4b08",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":326},
            "size":{
              "width":808,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/岗位管理/u47_line.png"}},
{
          "id":"e5da7a06e685451dbd81c7ff18bf726c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":220},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f739fbf8a092430f8a9a381c31a0bf31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":392,
                  "y":220},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1939798746d44f394c2fa40aed20feb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":260},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa5be8499a6c4b3fa2938f01a99456c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":392,
                  "y":260},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4a6cacda9bf4b54a586db5917206eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":300},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e915545fc3d94d0992aeed25d7fcc83d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":392,
                  "y":300},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80066f76c8bc44808202fbb1c2b90a10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":220},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d44aa2797ee144189527c95c53a2035e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":220},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86c86eee0f69434a8e18f82ddd745c3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":260},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18530f67a28841efa7aa168add12d6c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":260},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a93044640514189bfe7ae3f3b12b990",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":695,
              "y":220},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3e8ad1f1490401dbfe6bd27c43ebdbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":695,
                  "y":220},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a00b2337a4040409cf23064837c3c63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":695,
              "y":260},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66d90e81d06a4b9fbc485ce16f80a34a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":695,
                  "y":260},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "901e3164b9194d94abbf0cd7a97eea88":{
      "scriptId":"u0"},
    "d7b5db1e072c4059929d6938b372fbb5":{
      "scriptId":"u1"},
    "969aba5ac8834a0ba97db685a70fd36f":{
      "scriptId":"u2"},
    "c9eb59b31d2a4851af3e45a9b02f1762":{
      "scriptId":"u3"},
    "eb5a4c6b9b2547c3b1a73b186fc7bf8c":{
      "scriptId":"u4"},
    "a8884cdea0cd477c8162df9f69dfcece":{
      "scriptId":"u5"},
    "7de40b2b3f0643a7b773fc99409a5312":{
      "scriptId":"u6"},
    "2f082a500e5b4bbb8178d525bf842540":{
      "scriptId":"u7"},
    "cd235d8b50db46258d05c75434641636":{
      "scriptId":"u8"},
    "628c42deba6c4cbf97359258a80d3a29":{
      "scriptId":"u9"},
    "a12244bbfc4f461c8ae2771ef667994b":{
      "scriptId":"u10"},
    "3411813979f0414196d83ccb91673240":{
      "scriptId":"u11"},
    "021bc7671d41454d93dff979c63e20d1":{
      "scriptId":"u12"},
    "4eda180b97db4c939d8f24f192db3121":{
      "scriptId":"u13"},
    "6dc785763ad5454085d1d1efa4d464bc":{
      "scriptId":"u14"},
    "063f47758c2740389c482d65893025d6":{
      "scriptId":"u15"},
    "c4add9095a2e45d6907380c4368b6b83":{
      "scriptId":"u16"},
    "730a90dca7d34d4cb85546a4161df34d":{
      "scriptId":"u17"},
    "0c6767c99d7a4314a008670130f597b6":{
      "scriptId":"u18"},
    "f2ba793ba99d4c9ebaa57eda63dbe334":{
      "scriptId":"u19"},
    "a0baf79f0a0e44cab22ff8f6cc427576":{
      "scriptId":"u20"},
    "d50690fd1ef249fa95e011d0530b525e":{
      "scriptId":"u21"},
    "e7d09bed55ab4d4daefeabb8ce17104b":{
      "scriptId":"u22"},
    "b5f1ae2bdb95408fa8154989c99222ff":{
      "scriptId":"u23"},
    "61507530ab9249d3ad8182c4ddced087":{
      "scriptId":"u24"},
    "f23548b5e40f4ecda8364a3e5ec001c6":{
      "scriptId":"u25"},
    "8ffdd7739aa045978d9d763449faf948":{
      "scriptId":"u26"},
    "429a767c107f42f5a69ff840b83a8820":{
      "scriptId":"u27"},
    "477547bc32004e2bbfc56f5eacfd057d":{
      "scriptId":"u28"},
    "14dc4e6a1a324468b566ee026cfb6d4b":{
      "scriptId":"u29"},
    "44993853252d4065a67e493df92a2811":{
      "scriptId":"u30"},
    "6d49830f741f4071a75c5609ae110ef5":{
      "scriptId":"u31"},
    "243030f4bf3a46fc9c03fa772ce89aa0":{
      "scriptId":"u32"},
    "764e618774d24ec9b974bfdca7f5f3e2":{
      "scriptId":"u33"},
    "1497c348ce8d46c9bf6b5aee722757c2":{
      "scriptId":"u34"},
    "0e21cd5a73fc4a44949bd47a15ca3b3b":{
      "scriptId":"u35"},
    "063626df56224cb7a0f9d9bd163090b7":{
      "scriptId":"u36"},
    "edf1475813404c42b5154b50e88c2b21":{
      "scriptId":"u37"},
    "53c09d30c14b43dbaa3e7801c4efc682":{
      "scriptId":"u38"},
    "9d6a4b2bc99f4c8e848ea285378baa1b":{
      "scriptId":"u39"},
    "de152dc4546c4afba3c722ec312bc8e4":{
      "scriptId":"u40"},
    "717d2e9407e74821aa93753f6e4bca1c":{
      "scriptId":"u41"},
    "f5635fbd9bea47c6bad2417e337b39aa":{
      "scriptId":"u42"},
    "b5268c316ee242abbb27e68a0273c2d9":{
      "scriptId":"u43"},
    "5f4001b8930144d2992b0d3beb6eb241":{
      "scriptId":"u44"},
    "39e6a3534d454e9080d1fbb55d511bd9":{
      "scriptId":"u45"},
    "11285706eda44597a819165e979e4b08":{
      "scriptId":"u46"},
    "e5da7a06e685451dbd81c7ff18bf726c":{
      "scriptId":"u47"},
    "f739fbf8a092430f8a9a381c31a0bf31":{
      "scriptId":"u48"},
    "b1939798746d44f394c2fa40aed20feb":{
      "scriptId":"u49"},
    "fa5be8499a6c4b3fa2938f01a99456c9":{
      "scriptId":"u50"},
    "e4a6cacda9bf4b54a586db5917206eb1":{
      "scriptId":"u51"},
    "e915545fc3d94d0992aeed25d7fcc83d":{
      "scriptId":"u52"},
    "80066f76c8bc44808202fbb1c2b90a10":{
      "scriptId":"u53"},
    "d44aa2797ee144189527c95c53a2035e":{
      "scriptId":"u54"},
    "86c86eee0f69434a8e18f82ddd745c3f":{
      "scriptId":"u55"},
    "18530f67a28841efa7aa168add12d6c6":{
      "scriptId":"u56"},
    "6a93044640514189bfe7ae3f3b12b990":{
      "scriptId":"u57"},
    "d3e8ad1f1490401dbfe6bd27c43ebdbb":{
      "scriptId":"u58"},
    "6a00b2337a4040409cf23064837c3c63":{
      "scriptId":"u59"},
    "66d90e81d06a4b9fbc485ce16f80a34a":{
      "scriptId":"u60"}}});