$axure.loadCurrentPage({
  "url":"发布岗位.html",
  "generationDate":new Date(1446453255730.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"72ebfb10566c4ceeafbdb05fc02a6aab",
    "type":"Axure:Page",
    "name":"发布岗位",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"99e8de4bca9e4810b1edbee8fc7c5916",
          "label":"岗位发布面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":100},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"adc2663a58d6442c8daf8a1242894089",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"37eb10bfb18844d184acbe540cb8bf22",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "size":{
                      "width":1270,
                      "height":550},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0afbd5ece984f0092d0579bbee7110e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "size":{
                          "width":1270,
                          "height":550},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发布岗位/u1.png"}},
{
                  "id":"535cc389acac4fa8afcc22f348e2f097",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":210,
                      "y":487},
                    "size":{
                      "width":200,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5f6c7067dc141378e822819ec588bbf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":210,
                          "y":487},
                        "size":{
                          "width":200,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6b8f8d1e9379472696c20be20b7b1e7d",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":26,
                      "y":30},
                    "size":{
                      "width":1220,
                      "height":497},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd1b9b74ffcc4d138d42cb6c39b5a961",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":26,
                          "y":30},
                        "size":{
                          "width":1220,
                          "height":497},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发布岗位/u5.png"}},
{
                  "id":"f620c05c9e9940b7a6f93d7b4cf50a08",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":418,
                      "y":154},
                    "size":{
                      "width":275,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"4ed069d2e2a74f65b009d73ab3b500c4",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":145,
                      "y":259},
                    "size":{
                      "width":70,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"47c683073ab54e66bd622b7e13999f7a",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":226,
                      "y":259},
                    "size":{
                      "width":75,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"986e2d9b9b8745d8997613f4e239ef6e",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":144,
                      "y":429},
                    "size":{
                      "width":136,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"8b197c1bfd5a4ab3afb84a1cde7bc69e",
                  "label":"纳入问题库",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":173,
                      "y":479},
                    "size":{
                      "width":111,
                      "height":33},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a5b2c8fbbd3491da8a3276a542647c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":173,
                          "y":479},
                        "size":{
                          "width":111,
                          "height":33},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发布岗位/纳入问题库_u11.png"}},
{
                  "id":"1b3122a4d487401ea507c6f53e14fc22",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":53,
                      "y":158},
                    "size":{
                      "width":84,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"242e83a2e3f94805939a758e5caf93df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":53,
                          "y":158},
                        "size":{
                          "width":84,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e2d516f6e9a849deb17f17e0fad47894",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":53,
                      "y":61},
                    "size":{
                      "width":88,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"287e89155ef74c20b4ee997ed1a532fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":53,
                          "y":61},
                        "size":{
                          "width":88,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7761ef58363d46638e8ac527828422ea",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":324,
                      "y":161},
                    "size":{
                      "width":84,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8314a7e06a9d4c47a86410e461d39124",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":324,
                          "y":161},
                        "size":{
                          "width":84,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f332e6295f1048c7949a3f93d04b0178",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":40,
                      "y":266},
                    "size":{
                      "width":88,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d11b4cc264b4ff181e55e274f6e1abb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":40,
                          "y":266},
                        "size":{
                          "width":88,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d95294d6e7f444589959f43ea3f2fb2a",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":324,
                      "y":324},
                    "size":{
                      "width":88,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6e669201c40d42e1a42d172a4c16ebfd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":324,
                          "y":324},
                        "size":{
                          "width":88,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a74d4020e2ed400d8f40eab56fdfe501",
                  "label":"工作地址文本框",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":144,
                      "y":372},
                    "size":{
                      "width":549,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示/隐藏元件",
                              "objectsToFades":[]}]}]}},
                  "tabbable":true},
{
                  "id":"82c2282eb15e438686d78296333275ce",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":53,
                      "y":379},
                    "size":{
                      "width":84,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4aac3f64244d42faa2771c6caf7490c3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":53,
                          "y":379},
                        "size":{
                          "width":84,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7c835eefc48742a19947899951a1e305",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":53,
                      "y":436},
                    "size":{
                      "width":84,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6741ddc42e54eab84021ded490a82bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":53,
                          "y":436},
                        "size":{
                          "width":84,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e958874f4aa843b18139642420c94141",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":324,
                      "y":436},
                    "size":{
                      "width":88,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67114fbc1b82471cbe020419b662f2df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":324,
                          "y":436},
                        "size":{
                          "width":88,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"83a8dcb4bad945a1a31083656c0edfc2",
                  "label":"保存",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":52,
                      "y":479},
                    "size":{
                      "width":94,
                      "height":33},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"311dd42a697147f5975f9790114f4f6b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":52,
                          "y":479},
                        "size":{
                          "width":94,
                          "height":33},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/发布岗位/保存_u30.png"}},
{
                  "id":"7d6ae2ed316a4850aca4e8db86564d96",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":418,
                      "y":317},
                    "size":{
                      "width":123,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"060f6bf7a8fd462ea3f14a267a133089",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":548,
                      "y":317},
                    "size":{
                      "width":145,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"32425b716ee64549a143fbb38ae54c37",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":145,
                      "y":154},
                    "size":{
                      "width":155,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"fa2ccdc96bdc4466bed72b2fa1e0e609",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":142,
                      "y":54},
                    "size":{
                      "width":549,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"9ac21b45555549d5b9b55d4d2489d379",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":420,
                      "y":429},
                    "size":{
                      "width":221,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"a316856c751949bab147a6b23ba8d7c3",
                  "label":"纳入问题库3",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":644,
                      "y":430},
                    "size":{
                      "width":52,
                      "height":29},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84614bef79454c33b30cec0c9f86c57d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":644,
                          "y":430},
                        "size":{
                          "width":52,
                          "height":29},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/审核普通岗位/纳入问题库3_u90.png"}},
{
                  "id":"8911c726f7bb408ea685905f194cff13",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":418,
                      "y":207},
                    "size":{
                      "width":120,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"b213895f812e40dd8e96bbe5d65c164e",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":548,
                      "y":207},
                    "size":{
                      "width":145,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"aecaf527180b418684030ab74470e170",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":324,
                      "y":212},
                    "size":{
                      "width":88,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5161360e87c1435f877e082d36f3e289",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":324,
                          "y":212},
                        "size":{
                          "width":88,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9989ae50af8641238d7d124c0e7c39b0",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":53,
                      "y":323},
                    "size":{
                      "width":80,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3400347df354252aeae41b94e40e341",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":53,
                          "y":323},
                        "size":{
                          "width":80,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aa56aaeaaac841848d1c1890392e49ad",
                  "label":"岗位描述&岗位标签",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":727,
                      "y":55},
                    "size":{
                      "width":491,
                      "height":406}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"ef471c08e57b42c0a8419e4d3ba976fe",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"1481fa4ab9014272be3cbf9cdf959413",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2},
                            "location":{
                              "x":0,
                              "y":33},
                            "size":{
                              "width":491,
                              "height":340},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"298caf152994412290fd474c4905cc0c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"15px",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF2F2F2},
                                "location":{
                                  "x":0,
                                  "y":33},
                                "size":{
                                  "width":491,
                                  "height":340},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFCCCCCC}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/发布岗位/u46.png"}},
{
                          "id":"86606c3bf116432791defbd0fdfe70cc",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "size":{
                              "width":145,
                              "height":24}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"62a887d6edcb46998dfde750dc75b760",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"20px",
                                "size":{
                                  "width":145,
                                  "height":24}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"8525a422a9af4fd49a293a45a0d45aaf",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textArea",
                          "styleType":"textArea",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "location":{
                              "x":0,
                              "y":35},
                            "size":{
                              "width":489,
                              "height":372}},
                          "adaptiveStyles":{
}}]},
{
                      "id":"8665771ec47d4ebcb5950ff86bd4c7c8",
                      "label":"状态2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"1718f969d55b42678eaaf7a0d2a4528a",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"20px",
                            "location":{
                              "x":30,
                              "y":2},
                            "size":{
                              "width":145,
                              "height":24}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"fe45c0f197f548858c3703ee83117674",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"20px",
                                "location":{
                                  "x":30,
                                  "y":2},
                                "size":{
                                  "width":145,
                                  "height":24}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"1ca7044d46d1496483ff44398c2a5418",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2},
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":491,
                              "height":370},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7df70ea41f234f8ab1000591bf82c0ed",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"15px",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF2F2F2},
                                "location":{
                                  "x":0,
                                  "y":36},
                                "size":{
                                  "width":491,
                                  "height":370},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFCCCCCC}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/发布岗位/u53.png"}},
{
                          "id":"14059992683c4721abab8347c70c0180",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "location":{
                              "x":24,
                              "y":67},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"6071fc0436034db1b9ba0c4d4929f9b3",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "location":{
                              "x":24,
                              "y":137},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"f47c9fea1b094f029a142a2c1c8d2bc5",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "location":{
                              "x":24,
                              "y":206},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"aff3f53ea88c40c4906738654c11733a",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "location":{
                              "x":24,
                              "y":276},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"12a296f675e14648bfdf4416fda43f79",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "location":{
                              "x":24,
                              "y":348},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"2cd735592ed444acae5d1df89c559f50",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "location":{
                              "x":188,
                              "y":67},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"7b438c85bbdd4c2b9bb9310b4a7144fb",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "location":{
                              "x":188,
                              "y":137},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"98dd2fa77df14762be6621b1eb4c6711",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "location":{
                              "x":188,
                              "y":206},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"6399de051c8d41b5ae9d8709646fb0c3",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "location":{
                              "x":188,
                              "y":278},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"ab082ed6dab64d1a9ecbbdace9a92682",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "location":{
                              "x":188,
                              "y":348},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"e19d855e6d554e5eb2d32864b6bd1097",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "location":{
                              "x":348,
                              "y":67},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"bebf18c23e56441e9f166bd9d3380e61",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "location":{
                              "x":348,
                              "y":137},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"6a085c385a904aec954365fc406b04b1",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "location":{
                              "x":348,
                              "y":206},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"db8fb49ab71d4c0eaaa7a9a0c9f262c2",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "location":{
                              "x":348,
                              "y":278},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"37b7b734011e440c8aec5d6a2261f782",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "location":{
                              "x":348,
                              "y":348},
                            "size":{
                              "width":119,
                              "height":31}},
                          "adaptiveStyles":{
}},
{
                          "id":"3c6344e0c5924e72aa5128af235d229f",
                          "label":"",
                          "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "location":{
                              "x":2,
                              "y":0},
                            "size":{
                              "width":26,
                              "height":26}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"74347ebc5bc84e2e8d8b0f64af31221b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"aa56aaeaaac841848d1c1890392e49ad",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"15px",
                                "location":{
                                  "x":2,
                                  "y":0},
                                "size":{
                                  "width":26,
                                  "height":26}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/发布岗位审核/u242.png"}}]}]},
{
                  "id":"c38a9f74d5614d99a7a5e56d6818daaf",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":144,
                      "y":317},
                    "size":{
                      "width":156,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"a3dc6150f7374017960964d48c5f75b1",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":52,
                      "y":105},
                    "size":{
                      "width":84,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ae3e95040be4a68a556e76f2564f450",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":52,
                          "y":105},
                        "size":{
                          "width":84,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d3c356450af843bf98a35a8c0f533da3",
                  "label":"薪资单位",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":548,
                      "y":105},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a85bda661d8d4d728cccff8b0677a0c7",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"e9de52f62d9d4d699a10d7fda6633d43",
                          "label":"",
                          "parentDynamicPanel":"d3c356450af843bf98a35a8c0f533da3",
                          "type":"comboBox",
                          "styleType":"comboBox",
                          "visible":true,
                          "style":{
                            "fontSize":"15px",
                            "size":{
                              "width":145,
                              "height":31}},
                          "adaptiveStyles":{
}}]},
{
                      "id":"180bb24e72d24e7db507c9950b0d5b52",
                      "label":"状态2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"a3e50056ca3b4d76b72fad78b1722c5d",
                          "label":"",
                          "parentDynamicPanel":"d3c356450af843bf98a35a8c0f533da3",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2},
                            "size":{
                              "width":145,
                              "height":32}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1d67d87d96c64379b5237673a26be2cc",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"d3c356450af843bf98a35a8c0f533da3",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "verticalAlignment":"middle",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF2F2F2},
                                "size":{
                                  "width":145,
                                  "height":32}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/发布岗位/u77.png"}}]}]},
{
                  "id":"56bd2eaa076d44fd9f583823ea0aebf2",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":324,
                      "y":106},
                    "size":{
                      "width":84,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfb97c7d6df2469894eb795837d2e351",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":324,
                          "y":106},
                        "size":{
                          "width":84,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"92f0fd71e23c4ccfa3539ed30d4ce709",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":418,
                      "y":105},
                    "size":{
                      "width":120,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"07e1806b66fb4149aa544bb00ebd5caf",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":146,
                      "y":105},
                    "size":{
                      "width":154,
                      "height":31}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onSelectionChange":{
                      "description":"OnSelectionChange",
                      "cases":[{
                          "description":"用例 1<br> (If 选中项文字 This = &quot;普通岗位&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetSelectedOption",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":true,
                                  "isFocused":false,
                                  "isTarget":false}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"普通岗位",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 岗位描述&amp;岗位标签 to 状态1 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["aa56aaeaaac841848d1c1890392e49ad"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 薪资单位 to 状态1 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["d3c356450af843bf98a35a8c0f533da3"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"用例 2<br> (Else If 选中项文字 This = &quot;抢单岗位&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetSelectedOption",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":true,
                                  "isFocused":false,
                                  "isTarget":false}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"抢单岗位",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 岗位描述&amp;岗位标签 to 状态2 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["aa56aaeaaac841848d1c1890392e49ad"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 薪资单位 to 状态2 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["d3c356450af843bf98a35a8c0f533da3"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]}]}}},
{
                  "id":"2f873a3a419c49cb8ea943b32d13dd7e",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":145,
                      "y":207},
                    "size":{
                      "width":155,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"ef546031eed745a3b44d903c070c2f40",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":326,
                      "y":259},
                    "size":{
                      "width":79,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"e3333702b384467ab57a3a6ac6610c00",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":416,
                      "y":259},
                    "size":{
                      "width":85,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"9447ab32077a43528a8f331943b437b4",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":528,
                      "y":259},
                    "size":{
                      "width":74,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"5d3f4572d7cf4567a6d02b3fa088f18d",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":612,
                      "y":259},
                    "size":{
                      "width":79,
                      "height":31}},
                  "adaptiveStyles":{
}},
{
                  "id":"9c42d74534cc45dd8ca99e0cdc1c97f3",
                  "label":"",
                  "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "location":{
                      "x":53,
                      "y":213},
                    "size":{
                      "width":84,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e28d91791cf24bb899d39bf385852f80",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"99e8de4bca9e4810b1edbee8fc7c5916",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "location":{
                          "x":53,
                          "y":213},
                        "size":{
                          "width":84,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"f48b3a61f4714e5cb81dea35cb0756ab",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":717},
            "size":{
              "width":1270,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/审核普通岗位/u43_line.png"}},
{
          "id":"620abc5520c5403c95b2fe3e4f458f44",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":20,
              "y":690},
            "size":{
              "width":52,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0afe5725eea44a11815b073b2b058481",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":690},
                "size":{
                  "width":52,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aad34d68760442f823c6bb6916f9ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"15px",
            "location":{
              "x":20,
              "y":737},
            "size":{
              "width":414,
              "height":194}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f12fc402d1478489972a4a96b823f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"15px",
                "location":{
                  "x":20,
                  "y":737},
                "size":{
                  "width":414,
                  "height":194}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a7356e6de8143b4aac136b698f8433a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":448,
              "y":737},
            "size":{
              "width":414,
              "height":194}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd582064f86541b690b9c9efa63bdb39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":448,
                  "y":737},
                "size":{
                  "width":414,
                  "height":194}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1004b6319b046ffacc8f7c1fad2e597",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"14px",
            "location":{
              "x":876,
              "y":737},
            "size":{
              "width":414,
              "height":194}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9f703491fe745b0b42da81ec85ddc51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"14px",
                "location":{
                  "x":876,
                  "y":737},
                "size":{
                  "width":414,
                  "height":194}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "99e8de4bca9e4810b1edbee8fc7c5916":{
      "scriptId":"u0"},
    "37eb10bfb18844d184acbe540cb8bf22":{
      "scriptId":"u1"},
    "c0afbd5ece984f0092d0579bbee7110e":{
      "scriptId":"u2"},
    "535cc389acac4fa8afcc22f348e2f097":{
      "scriptId":"u3"},
    "e5f6c7067dc141378e822819ec588bbf":{
      "scriptId":"u4"},
    "6b8f8d1e9379472696c20be20b7b1e7d":{
      "scriptId":"u5"},
    "bd1b9b74ffcc4d138d42cb6c39b5a961":{
      "scriptId":"u6"},
    "f620c05c9e9940b7a6f93d7b4cf50a08":{
      "scriptId":"u7"},
    "4ed069d2e2a74f65b009d73ab3b500c4":{
      "scriptId":"u8"},
    "47c683073ab54e66bd622b7e13999f7a":{
      "scriptId":"u9"},
    "986e2d9b9b8745d8997613f4e239ef6e":{
      "scriptId":"u10"},
    "8b197c1bfd5a4ab3afb84a1cde7bc69e":{
      "scriptId":"u11"},
    "4a5b2c8fbbd3491da8a3276a542647c0":{
      "scriptId":"u12"},
    "1b3122a4d487401ea507c6f53e14fc22":{
      "scriptId":"u13"},
    "242e83a2e3f94805939a758e5caf93df":{
      "scriptId":"u14"},
    "e2d516f6e9a849deb17f17e0fad47894":{
      "scriptId":"u15"},
    "287e89155ef74c20b4ee997ed1a532fc":{
      "scriptId":"u16"},
    "7761ef58363d46638e8ac527828422ea":{
      "scriptId":"u17"},
    "8314a7e06a9d4c47a86410e461d39124":{
      "scriptId":"u18"},
    "f332e6295f1048c7949a3f93d04b0178":{
      "scriptId":"u19"},
    "7d11b4cc264b4ff181e55e274f6e1abb":{
      "scriptId":"u20"},
    "d95294d6e7f444589959f43ea3f2fb2a":{
      "scriptId":"u21"},
    "6e669201c40d42e1a42d172a4c16ebfd":{
      "scriptId":"u22"},
    "a74d4020e2ed400d8f40eab56fdfe501":{
      "scriptId":"u23"},
    "82c2282eb15e438686d78296333275ce":{
      "scriptId":"u24"},
    "4aac3f64244d42faa2771c6caf7490c3":{
      "scriptId":"u25"},
    "7c835eefc48742a19947899951a1e305":{
      "scriptId":"u26"},
    "e6741ddc42e54eab84021ded490a82bc":{
      "scriptId":"u27"},
    "e958874f4aa843b18139642420c94141":{
      "scriptId":"u28"},
    "67114fbc1b82471cbe020419b662f2df":{
      "scriptId":"u29"},
    "83a8dcb4bad945a1a31083656c0edfc2":{
      "scriptId":"u30"},
    "311dd42a697147f5975f9790114f4f6b":{
      "scriptId":"u31"},
    "7d6ae2ed316a4850aca4e8db86564d96":{
      "scriptId":"u32"},
    "060f6bf7a8fd462ea3f14a267a133089":{
      "scriptId":"u33"},
    "32425b716ee64549a143fbb38ae54c37":{
      "scriptId":"u34"},
    "fa2ccdc96bdc4466bed72b2fa1e0e609":{
      "scriptId":"u35"},
    "9ac21b45555549d5b9b55d4d2489d379":{
      "scriptId":"u36"},
    "a316856c751949bab147a6b23ba8d7c3":{
      "scriptId":"u37"},
    "84614bef79454c33b30cec0c9f86c57d":{
      "scriptId":"u38"},
    "8911c726f7bb408ea685905f194cff13":{
      "scriptId":"u39"},
    "b213895f812e40dd8e96bbe5d65c164e":{
      "scriptId":"u40"},
    "aecaf527180b418684030ab74470e170":{
      "scriptId":"u41"},
    "5161360e87c1435f877e082d36f3e289":{
      "scriptId":"u42"},
    "9989ae50af8641238d7d124c0e7c39b0":{
      "scriptId":"u43"},
    "c3400347df354252aeae41b94e40e341":{
      "scriptId":"u44"},
    "aa56aaeaaac841848d1c1890392e49ad":{
      "scriptId":"u45"},
    "1481fa4ab9014272be3cbf9cdf959413":{
      "scriptId":"u46"},
    "298caf152994412290fd474c4905cc0c":{
      "scriptId":"u47"},
    "86606c3bf116432791defbd0fdfe70cc":{
      "scriptId":"u48"},
    "62a887d6edcb46998dfde750dc75b760":{
      "scriptId":"u49"},
    "8525a422a9af4fd49a293a45a0d45aaf":{
      "scriptId":"u50"},
    "1718f969d55b42678eaaf7a0d2a4528a":{
      "scriptId":"u51"},
    "fe45c0f197f548858c3703ee83117674":{
      "scriptId":"u52"},
    "1ca7044d46d1496483ff44398c2a5418":{
      "scriptId":"u53"},
    "7df70ea41f234f8ab1000591bf82c0ed":{
      "scriptId":"u54"},
    "14059992683c4721abab8347c70c0180":{
      "scriptId":"u55"},
    "6071fc0436034db1b9ba0c4d4929f9b3":{
      "scriptId":"u56"},
    "f47c9fea1b094f029a142a2c1c8d2bc5":{
      "scriptId":"u57"},
    "aff3f53ea88c40c4906738654c11733a":{
      "scriptId":"u58"},
    "12a296f675e14648bfdf4416fda43f79":{
      "scriptId":"u59"},
    "2cd735592ed444acae5d1df89c559f50":{
      "scriptId":"u60"},
    "7b438c85bbdd4c2b9bb9310b4a7144fb":{
      "scriptId":"u61"},
    "98dd2fa77df14762be6621b1eb4c6711":{
      "scriptId":"u62"},
    "6399de051c8d41b5ae9d8709646fb0c3":{
      "scriptId":"u63"},
    "ab082ed6dab64d1a9ecbbdace9a92682":{
      "scriptId":"u64"},
    "e19d855e6d554e5eb2d32864b6bd1097":{
      "scriptId":"u65"},
    "bebf18c23e56441e9f166bd9d3380e61":{
      "scriptId":"u66"},
    "6a085c385a904aec954365fc406b04b1":{
      "scriptId":"u67"},
    "db8fb49ab71d4c0eaaa7a9a0c9f262c2":{
      "scriptId":"u68"},
    "37b7b734011e440c8aec5d6a2261f782":{
      "scriptId":"u69"},
    "3c6344e0c5924e72aa5128af235d229f":{
      "scriptId":"u70"},
    "74347ebc5bc84e2e8d8b0f64af31221b":{
      "scriptId":"u71"},
    "c38a9f74d5614d99a7a5e56d6818daaf":{
      "scriptId":"u72"},
    "a3dc6150f7374017960964d48c5f75b1":{
      "scriptId":"u73"},
    "5ae3e95040be4a68a556e76f2564f450":{
      "scriptId":"u74"},
    "d3c356450af843bf98a35a8c0f533da3":{
      "scriptId":"u75"},
    "e9de52f62d9d4d699a10d7fda6633d43":{
      "scriptId":"u76"},
    "a3e50056ca3b4d76b72fad78b1722c5d":{
      "scriptId":"u77"},
    "1d67d87d96c64379b5237673a26be2cc":{
      "scriptId":"u78"},
    "56bd2eaa076d44fd9f583823ea0aebf2":{
      "scriptId":"u79"},
    "bfb97c7d6df2469894eb795837d2e351":{
      "scriptId":"u80"},
    "92f0fd71e23c4ccfa3539ed30d4ce709":{
      "scriptId":"u81"},
    "07e1806b66fb4149aa544bb00ebd5caf":{
      "scriptId":"u82"},
    "2f873a3a419c49cb8ea943b32d13dd7e":{
      "scriptId":"u83"},
    "ef546031eed745a3b44d903c070c2f40":{
      "scriptId":"u84"},
    "e3333702b384467ab57a3a6ac6610c00":{
      "scriptId":"u85"},
    "9447ab32077a43528a8f331943b437b4":{
      "scriptId":"u86"},
    "5d3f4572d7cf4567a6d02b3fa088f18d":{
      "scriptId":"u87"},
    "9c42d74534cc45dd8ca99e0cdc1c97f3":{
      "scriptId":"u88"},
    "e28d91791cf24bb899d39bf385852f80":{
      "scriptId":"u89"},
    "f48b3a61f4714e5cb81dea35cb0756ab":{
      "scriptId":"u90"},
    "620abc5520c5403c95b2fe3e4f458f44":{
      "scriptId":"u91"},
    "0afe5725eea44a11815b073b2b058481":{
      "scriptId":"u92"},
    "8aad34d68760442f823c6bb6916f9ff7":{
      "scriptId":"u93"},
    "f1f12fc402d1478489972a4a96b823f3":{
      "scriptId":"u94"},
    "8a7356e6de8143b4aac136b698f8433a":{
      "scriptId":"u95"},
    "fd582064f86541b690b9c9efa63bdb39":{
      "scriptId":"u96"},
    "f1004b6319b046ffacc8f7c1fad2e597":{
      "scriptId":"u97"},
    "e9f703491fe745b0b42da81ec85ddc51":{
      "scriptId":"u98"}}});