$axure.loadCurrentPage({
  "url":"短息记录.html",
  "generationDate":new Date(1454224749599.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"7ef62b931a6949219d59515248ddfdaf",
    "type":"Axure:Page",
    "name":"短息记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"48aca3fc02a34fc29bacffdf2ff9bf42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":751,
              "height":450},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a29e7c43df24d12b0503f406a5c6af2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":751,
                  "height":450},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/短息记录/u0.png"}},
{
          "id":"e96a4ee247c74cbd8443081361ff6925",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":432}},
          "adaptiveStyles":{
},
          "masterId":"13d846b0d66247249857eec41359c1ee"},
{
          "id":"a68cf34c763f4313a44905e981bb509a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":230,
              "y":560},
            "size":{
              "width":200,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a407d03535fc4e1681de6e729dec9569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":230,
                  "y":560},
                "size":{
                  "width":200,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7342f9e864f644ab99cc1df50243ac49",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":40},
            "size":{
              "width":707,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0f18ffbdf4443aabb0cc414fb104bef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":141,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ad440ab799c54d1785ededb5ff7c4e89",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":141,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u20.png"}},
{
              "id":"49f1e98fb4d24ab4ad6b9d10780f2ff4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":141,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9aedd6c98f1c48ee87214aab2b500025",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":141,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u30.png"}},
{
              "id":"44b954d8d77c4db8b7833d1a369002d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":141,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3990098ab5349539001ab985e747a73",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":141,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u40.png"}},
{
              "id":"8a38bb6ac42b46fd93dc89d9fd4cbff9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":141,
                  "y":0},
                "size":{
                  "width":141,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a33f9826712499980634f8925acd727",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":141,
                      "y":0},
                    "size":{
                      "width":141,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u20.png"}},
{
              "id":"beacaeedef78402686d20f50e288bd7a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":141,
                  "y":30},
                "size":{
                  "width":141,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98a51349f02143fe8d1b21926bc616e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":141,
                      "y":30},
                    "size":{
                      "width":141,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u30.png"}},
{
              "id":"1275deb009614b4f9995de9386d6e0af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":141,
                  "y":66},
                "size":{
                  "width":141,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f26f93456bc64c23986b8d22c78690ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":141,
                      "y":66},
                    "size":{
                      "width":141,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u40.png"}},
{
              "id":"b67ff36f3b9e4ed39e6518b4f1c4bfe0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":282,
                  "y":0},
                "size":{
                  "width":141,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3ebeaa958f2644319b06fa32a5bbb2b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":282,
                      "y":0},
                    "size":{
                      "width":141,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u20.png"}},
{
              "id":"3036a504df634f73a845df903e6fd4f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":282,
                  "y":30},
                "size":{
                  "width":141,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8359cbd464354cd4968101425f605937",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":282,
                      "y":30},
                    "size":{
                      "width":141,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u30.png"}},
{
              "id":"9701e1183c6647c2840880a68769e030",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":282,
                  "y":66},
                "size":{
                  "width":141,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"750540bcbd7545359881a56fc30a45ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":282,
                      "y":66},
                    "size":{
                      "width":141,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u40.png"}},
{
              "id":"0da9ebb4949b4b0eba2127a3a651677a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":423,
                  "y":0},
                "size":{
                  "width":141,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a0b2bfad88cd45dfaf455f1ec22315c2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":423,
                      "y":0},
                    "size":{
                      "width":141,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u20.png"}},
{
              "id":"221a8031ae3f4da0a91927c9b0b85cf8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":423,
                  "y":30},
                "size":{
                  "width":141,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"26dd784c33f841e0b4597f2a8b6fa94c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":423,
                      "y":30},
                    "size":{
                      "width":141,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u30.png"}},
{
              "id":"06b07bb83621420fac6c6c0ed65da30a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":423,
                  "y":66},
                "size":{
                  "width":141,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"778e1dfc8a184a918608b50ea515e730",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":423,
                      "y":66},
                    "size":{
                      "width":141,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u40.png"}},
{
              "id":"ad3b87db869a4be9b9236810e2bef920",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":564,
                  "y":0},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0029ea1a03234af087c262b47dd2cd6d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":564,
                      "y":0},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u28.png"}},
{
              "id":"9463baf67c3a41fa93759d89a118a789",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":564,
                  "y":30},
                "size":{
                  "width":143,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"488d765850d84110a7f94fc687b30f63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":564,
                      "y":30},
                    "size":{
                      "width":143,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u38.png"}},
{
              "id":"aed3e42e7c4942709993dc35a8d1d1f3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":564,
                  "y":66},
                "size":{
                  "width":143,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d3362e187cd4fad863438e71a6ff2b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":564,
                      "y":66},
                    "size":{
                      "width":143,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/短息记录/u48.png"}}]}]}},
  "masters":{
    "13d846b0d66247249857eec41359c1ee":{
      "packageId":"13d846b0d66247249857eec41359c1ee",
      "type":"Axure:Master",
      "name":"翻页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9d40ad363eac4156a28eb0cf063c503b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF81BC43},
              "location":{
                "x":323,
                "y":0},
              "size":{
                "width":54,
                "height":17},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"3"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b36a2da2b63041a5a6f9a34582c5260f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF81BC43},
                  "location":{
                    "x":323,
                    "y":0},
                  "size":{
                    "width":54,
                    "height":17},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"3"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/支付宝取现流水/u54.png"}},
{
            "id":"ca05a5272a7f42a3b61819d340567624",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF81BC43},
              "location":{
                "x":259,
                "y":0},
              "size":{
                "width":54,
                "height":17},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"3"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a037ecaf7bd4af5956fe225e6e620c5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF81BC43},
                  "location":{
                    "x":259,
                    "y":0},
                  "size":{
                    "width":54,
                    "height":17},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"3"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/支付宝取现流水/u54.png"}},
{
            "id":"ffaab904ad3a48a8aa0e3c8c3ad3dd3f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF81BC43},
              "location":{
                "x":215,
                "y":0},
              "size":{
                "width":34,
                "height":17},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"3"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa915d5c8b954538915e2f38ed2d1026",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF81BC43},
                  "location":{
                    "x":215,
                    "y":0},
                  "size":{
                    "width":34,
                    "height":17},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"3"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/支付宝取现流水/u58.png"}},
{
            "id":"6032fd48ad2543859366b4e250ae611d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF81BC43},
              "location":{
                "x":171,
                "y":0},
              "size":{
                "width":34,
                "height":17},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"3"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67af25523ec54b6980b5d71f0e7fee04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF81BC43},
                  "location":{
                    "x":171,
                    "y":0},
                  "size":{
                    "width":34,
                    "height":17},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"3"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/支付宝取现流水/u58.png"}},
{
            "id":"8fc88888446746f7a38281bc965a20db",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF81BC43},
              "location":{
                "x":127,
                "y":0},
              "size":{
                "width":34,
                "height":17},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"3"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef735e8d09ee4edf9a5495fdf3b545b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF81BC43},
                  "location":{
                    "x":127,
                    "y":0},
                  "size":{
                    "width":34,
                    "height":17},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"3"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/支付宝取现流水/u58.png"}},
{
            "id":"f6870d0b45474f3497c11f810bd588d9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF81BC43},
              "location":{
                "x":64,
                "y":0},
              "size":{
                "width":54,
                "height":17},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"3"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a2d2674ff897493b80c232334d9ef614",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF81BC43},
                  "location":{
                    "x":64,
                    "y":0},
                  "size":{
                    "width":54,
                    "height":17},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"3"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/支付宝取现流水/u54.png"}},
{
            "id":"ed1a8f9c1b60465da4b5f2967982cc97",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF81BC43},
              "size":{
                "width":54,
                "height":17},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"3"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f4f3eaf8a81f4a50bdb157633f1fc826",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF81BC43},
                  "size":{
                    "width":54,
                    "height":17},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"3"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/支付宝取现流水/u54.png"}}]}}},
  "objectPaths":{
    "48aca3fc02a34fc29bacffdf2ff9bf42":{
      "scriptId":"u0"},
    "9a29e7c43df24d12b0503f406a5c6af2":{
      "scriptId":"u1"},
    "e96a4ee247c74cbd8443081361ff6925":{
      "scriptId":"u2",
      "9d40ad363eac4156a28eb0cf063c503b":{
        "scriptId":"u3"},
      "b36a2da2b63041a5a6f9a34582c5260f":{
        "scriptId":"u4"},
      "ca05a5272a7f42a3b61819d340567624":{
        "scriptId":"u5"},
      "0a037ecaf7bd4af5956fe225e6e620c5":{
        "scriptId":"u6"},
      "ffaab904ad3a48a8aa0e3c8c3ad3dd3f":{
        "scriptId":"u7"},
      "fa915d5c8b954538915e2f38ed2d1026":{
        "scriptId":"u8"},
      "6032fd48ad2543859366b4e250ae611d":{
        "scriptId":"u9"},
      "67af25523ec54b6980b5d71f0e7fee04":{
        "scriptId":"u10"},
      "8fc88888446746f7a38281bc965a20db":{
        "scriptId":"u11"},
      "ef735e8d09ee4edf9a5495fdf3b545b7":{
        "scriptId":"u12"},
      "f6870d0b45474f3497c11f810bd588d9":{
        "scriptId":"u13"},
      "a2d2674ff897493b80c232334d9ef614":{
        "scriptId":"u14"},
      "ed1a8f9c1b60465da4b5f2967982cc97":{
        "scriptId":"u15"},
      "f4f3eaf8a81f4a50bdb157633f1fc826":{
        "scriptId":"u16"}},
    "a68cf34c763f4313a44905e981bb509a":{
      "scriptId":"u17"},
    "a407d03535fc4e1681de6e729dec9569":{
      "scriptId":"u18"},
    "7342f9e864f644ab99cc1df50243ac49":{
      "scriptId":"u19"},
    "b0f18ffbdf4443aabb0cc414fb104bef":{
      "scriptId":"u20"},
    "ad440ab799c54d1785ededb5ff7c4e89":{
      "scriptId":"u21"},
    "8a38bb6ac42b46fd93dc89d9fd4cbff9":{
      "scriptId":"u22"},
    "6a33f9826712499980634f8925acd727":{
      "scriptId":"u23"},
    "b67ff36f3b9e4ed39e6518b4f1c4bfe0":{
      "scriptId":"u24"},
    "3ebeaa958f2644319b06fa32a5bbb2b9":{
      "scriptId":"u25"},
    "0da9ebb4949b4b0eba2127a3a651677a":{
      "scriptId":"u26"},
    "a0b2bfad88cd45dfaf455f1ec22315c2":{
      "scriptId":"u27"},
    "ad3b87db869a4be9b9236810e2bef920":{
      "scriptId":"u28"},
    "0029ea1a03234af087c262b47dd2cd6d":{
      "scriptId":"u29"},
    "49f1e98fb4d24ab4ad6b9d10780f2ff4":{
      "scriptId":"u30"},
    "9aedd6c98f1c48ee87214aab2b500025":{
      "scriptId":"u31"},
    "beacaeedef78402686d20f50e288bd7a":{
      "scriptId":"u32"},
    "98a51349f02143fe8d1b21926bc616e4":{
      "scriptId":"u33"},
    "3036a504df634f73a845df903e6fd4f5":{
      "scriptId":"u34"},
    "8359cbd464354cd4968101425f605937":{
      "scriptId":"u35"},
    "221a8031ae3f4da0a91927c9b0b85cf8":{
      "scriptId":"u36"},
    "26dd784c33f841e0b4597f2a8b6fa94c":{
      "scriptId":"u37"},
    "9463baf67c3a41fa93759d89a118a789":{
      "scriptId":"u38"},
    "488d765850d84110a7f94fc687b30f63":{
      "scriptId":"u39"},
    "44b954d8d77c4db8b7833d1a369002d4":{
      "scriptId":"u40"},
    "a3990098ab5349539001ab985e747a73":{
      "scriptId":"u41"},
    "1275deb009614b4f9995de9386d6e0af":{
      "scriptId":"u42"},
    "f26f93456bc64c23986b8d22c78690ae":{
      "scriptId":"u43"},
    "9701e1183c6647c2840880a68769e030":{
      "scriptId":"u44"},
    "750540bcbd7545359881a56fc30a45ee":{
      "scriptId":"u45"},
    "06b07bb83621420fac6c6c0ed65da30a":{
      "scriptId":"u46"},
    "778e1dfc8a184a918608b50ea515e730":{
      "scriptId":"u47"},
    "aed3e42e7c4942709993dc35a8d1d1f3":{
      "scriptId":"u48"},
    "5d3362e187cd4fad863438e71a6ff2b7":{
      "scriptId":"u49"}}});