$axure.loadCurrentPage({
  "url":"拜访记录.html",
  "generationDate":new Date(1453101340856.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"a186e7d4f02a42daae3786e88d7a98e3",
    "type":"Axure:Page",
    "name":"拜访记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c0dc4e3876664c6981d5c50fc5a9377e",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":709,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8f336312afd4f1b922d114c3301b967",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":82,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f797b275d414eb29e2509e94df0c346",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":82,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u1.png"}},
{
              "id":"702efa88989a4d2d89e51d752fb7b7e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":29},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a0e419d240c745a0b2db24c6819f77f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":29},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u9.png"}},
{
              "id":"b7b7ecece03c4d59af317dcda7c95e7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":49},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"756fbb6e8d16413ea6943ba4fd85a9f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":49},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u17.png"}},
{
              "id":"7460eb25315d4cac907e0fd44d8a1383",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":82,
                  "y":0},
                "size":{
                  "width":95,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c1eaaad36de405989ac3674517a0e09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":82,
                      "y":0},
                    "size":{
                      "width":95,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u3.png"}},
{
              "id":"92bf2b661b0f4fca86c6b362dc277856",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":29},
                "size":{
                  "width":95,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe348cf9fec34bb6975d05b4a9829c17",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":82,
                      "y":29},
                    "size":{
                      "width":95,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u11.png"}},
{
              "id":"e1dc530837a44b4d83976f2e0ea561db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":49},
                "size":{
                  "width":95,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"03b8a884c6be46c29d45c4ee9e682b1e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":82,
                      "y":49},
                    "size":{
                      "width":95,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u19.png"}},
{
              "id":"1e54a685abdd4114809eeddabc2e4001",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":585,
                  "y":0},
                "size":{
                  "width":124,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2183ace2d741451da1ee8014d9dff0ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":585,
                      "y":0},
                    "size":{
                      "width":124,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u7.png"}},
{
              "id":"3db2fa5d07c145bd9e296523cd2679df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":585,
                  "y":29},
                "size":{
                  "width":124,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e52d16b1f8f435590fe64f6500afd43",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":585,
                      "y":29},
                    "size":{
                      "width":124,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u15.png"}},
{
              "id":"ad474bdedde14bc3846dd682f5df6ff6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":585,
                  "y":49},
                "size":{
                  "width":124,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7329e7a553b745ebbd009cc1aaea4ea3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":585,
                      "y":49},
                    "size":{
                      "width":124,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u23.png"}},
{
              "id":"ff2eac19b844402abc7c0879fbf2fb8b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":177,
                  "y":0},
                "size":{
                  "width":408,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c0a463b42084c69b184697f5f70a059",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":177,
                      "y":0},
                    "size":{
                      "width":408,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u5.png"}},
{
              "id":"41c24d133ca045f88137d99710ec480a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":177,
                  "y":29},
                "size":{
                  "width":408,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0d847376ecdc4bd589b03c685bd13c75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "location":{
                      "x":177,
                      "y":29},
                    "size":{
                      "width":408,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u13.png"}},
{
              "id":"3098f60454cf414cafd9ebfc25f2d4f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":177,
                  "y":49},
                "size":{
                  "width":408,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"381b4907a9e841209978b3b69121e84f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "location":{
                      "x":177,
                      "y":49},
                    "size":{
                      "width":408,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访记录/u21.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "c0dc4e3876664c6981d5c50fc5a9377e":{
      "scriptId":"u0"},
    "c8f336312afd4f1b922d114c3301b967":{
      "scriptId":"u1"},
    "2f797b275d414eb29e2509e94df0c346":{
      "scriptId":"u2"},
    "7460eb25315d4cac907e0fd44d8a1383":{
      "scriptId":"u3"},
    "5c1eaaad36de405989ac3674517a0e09":{
      "scriptId":"u4"},
    "ff2eac19b844402abc7c0879fbf2fb8b":{
      "scriptId":"u5"},
    "6c0a463b42084c69b184697f5f70a059":{
      "scriptId":"u6"},
    "1e54a685abdd4114809eeddabc2e4001":{
      "scriptId":"u7"},
    "2183ace2d741451da1ee8014d9dff0ad":{
      "scriptId":"u8"},
    "702efa88989a4d2d89e51d752fb7b7e2":{
      "scriptId":"u9"},
    "a0e419d240c745a0b2db24c6819f77f8":{
      "scriptId":"u10"},
    "92bf2b661b0f4fca86c6b362dc277856":{
      "scriptId":"u11"},
    "fe348cf9fec34bb6975d05b4a9829c17":{
      "scriptId":"u12"},
    "41c24d133ca045f88137d99710ec480a":{
      "scriptId":"u13"},
    "0d847376ecdc4bd589b03c685bd13c75":{
      "scriptId":"u14"},
    "3db2fa5d07c145bd9e296523cd2679df":{
      "scriptId":"u15"},
    "3e52d16b1f8f435590fe64f6500afd43":{
      "scriptId":"u16"},
    "b7b7ecece03c4d59af317dcda7c95e7b":{
      "scriptId":"u17"},
    "756fbb6e8d16413ea6943ba4fd85a9f7":{
      "scriptId":"u18"},
    "e1dc530837a44b4d83976f2e0ea561db":{
      "scriptId":"u19"},
    "03b8a884c6be46c29d45c4ee9e682b1e":{
      "scriptId":"u20"},
    "3098f60454cf414cafd9ebfc25f2d4f2":{
      "scriptId":"u21"},
    "381b4907a9e841209978b3b69121e84f":{
      "scriptId":"u22"},
    "ad474bdedde14bc3846dd682f5df6ff6":{
      "scriptId":"u23"},
    "7329e7a553b745ebbd009cc1aaea4ea3":{
      "scriptId":"u24"}}});